### ISSUE TITLE
bugs and suggestion

### ISSUE THREAD

**Issue by Rogenar** [mariumbacchus/Soulslike-Weaponry#1]
In the SW-0.9.8.1 cloth version, when mjölnir is thrown, it comes to the interior of the inventory instead of coming with the main slot, making combat more difficult. and also mjolnir sometimes doesn't come back at all and gives a constant warning message in the chat section. She always writes a message (There is no Freyr Sword bound to you!) In the chat section. Kratos' battle ax was supposed to be a throwable and tangible weapon like the mjölnir.

**Comment by mariumbacchus** [comment]
Mjolnir works like a trident with Loyalty, if you throw it too far out of render distance or into the void, it will not return, just like a trident wouldn't. The warning "There is no Freyr Sword bound to you!" only prints when trying to use the keybinds to return Freyr Sword back to you when you have no Freyr Sword bound to you, the keybind has no effect on Mjolnir, only Freyr Sword (and maybe other summon weapons in the future).

**Comment by Rogenar** [comment]
Regardless of the distance, Mjolnir should still come back to the hand and land in one of the main slots. This is needed so that we can fight mjoilnir nonstop again after it comes back to hand.

**Comment by mariumbacchus** [comment]
I agree, I'll see what I can do about that issue.

**Comment by Rogenar** [comment]
I noticed something else while testing the gun. When I die after Mjolnir is cast, it doesn't come back when I respawn. And the fact that such a powerful weapon has 8 damage is very weak compared to other weapons. Leviathan axe and Mjolnir Must have at least 12 damage. It doesn't make sense for these two types of godlike weapons to have a stamina. These two weapons need to be unbreakable. But in return, their recipes should be made more difficult. Finally, like Mjolnir, the Leviathan Ax weapon needs to be a throwable and returnable weapon, depending on its owner.

**Comment by mariumbacchus** [comment]
You can always change the damage in the config if you feel like they are too low. I am considering making Leviathan Axe return like Mjolnir and even have an interaction if they hit one-another. It's only natural that Mjolnir won't return to you when you are... well... dead, it has no owner to go to. Mjolnir may be weak in damage and has long cooldowns, but that's also because it has so many abilities, so compensation is needed. I may increase the speed Mjolnir returns to the player, and set a max distance it can travel so we can avoid losing it to render distance and such.

**Comment by Rogenar** [comment]
It would be nice to have Mjolnir back in our inventory after being resurrected. Because it is not an easy weapon to make. Yes, Leviathan ax and Mjolnir mid-air collision effect would be nice. Thus, it would be a different experience to live the god of war ragnarok game in minecraft. I don't know how to change hit damage. It would be nice to have the O status updated with increased damage in the next patch. Also, since I will play by installing the mod on the server, it will be difficult for me to adjust the hit damage.

**Comment by mariumbacchus** [comment]
Understandable, I'll see what I can do.

**Comment by Rogenar** [comment]
Before I forget, I would like to make one more suggestion. It would be nice to have a feature like being able to fly with Mjolnir.

**Comment by Rogenar** [comment]
With the new updated version, mjolnir errors are gone. Leviathan ax can be thrown like mjolnir and returned to the hand again. But the damage of mjolnir is still very low and I don't know how to adjust it. Is it possible to fix leviathan ax and mjolnir base damage to 12 with the next update?
