### ISSUE TITLE
game crashes when I summon a boss with the Essence of Eventide

### ISSUE THREAD

**Issue by JamingDE** [mariumbacchus/Soulslike-Weaponry#100]
As soon as I summon the boss, the game crashes.

minecraft version: 1.20.1 fabric
cpu: amd ryzen 5 4500,
gpu: readon rx 6600 XT
ram: 32gb, 12gb for minecraft
gamemode: singleplayer, hardcore

How to replicate;
Go to the End, defeat the Ender Dragon, and summon the boss with the Old Moon Altar. Then, as soon as the boss fight begins, Minecraft crashes.

Crash-Report:
[crash-2024-03-23_00.50.22-client.txt](https://github.com/mariumbacchus/Soulslike-Weaponry/files/14733853/crash-2024-03-23_00.50.22-client.txt)

Log:
[latest.log](https://github.com/mariumbacchus/Soulslike-Weaponry/files/14733854/latest.log)

i dont know wtich of those mods was the problem but without iris, sodium and indium it workes.

pls help, its really anoing. the other bosses work.

update: the second time i tried to fight the boss, minecraft crashed. even without sudium, iris and indium

**Comment by JamingDE** [comment]
update: the secod time i tried to fight the boss, minecraft crashed agan, even without sodium, iris and indium.

**Comment by mariumbacchus** [comment]
`java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbquests.quest.BaseQuestFile.isPlayerOnTeam(net.minecraft.class_1657, dev.ftb.mods.ftbquests.quest.TeamData)" because "this.file" is null
	at dev.ftb.mods.ftbquests.quest.TeamData.getOrCreatePlayerData(TeamData.java:708)
`
This line right here tells me that this isn't a soulsweaponry issue, rather a FTB quests one.

**Comment by JamingDE** [comment]
but i dont use ftb quests anymore, bc it crashed my game to. i deletet the jar file in my moddingfolder.
