### ISSUE TITLE
Darkmoon Longbow no longer has a cooldown with Unbreaking V

### ISSUE THREAD

**Issue by Frontear** [mariumbacchus/Soulslike-Weaponry#101]
Hi, I'm from LunaPixelStudios! A user recently reported to me an issue that was causing the Darkmoon Longbow to have 0 cooldown, allowing it to be spammed and even cause a lot of lag. This occurred only when the bow had Unbreaking V on it (this is possible due to our modpack which raises the cap on some enchantments).

This bug can cause severe lag and even crash people, likely from all the particle rendering.

I'll attach a video recorded from the user of the bug:

https://github.com/mariumbacchus/Soulslike-Weaponry/assets/31909298/348c46d0-3124-4d3d-989e-d88e8341d3ce

**Comment by mariumbacchus** [comment]
Yeah, coded it with an unbreaking level cap of 3 in mind, will fix that.

**Comment by Frontear** [comment]
Thanks a lot for the quick resolution!
