### ISSUE TITLE
SW 1.1.0 [1.20/1.20.1] Issue: Withered Demon way too loud

### ISSUE THREAD

**Issue by WillXYZ9656** [mariumbacchus/Soulslike-Weaponry#105]
Really enjoying the mod so far! The only issue I've come across is that whenever I'm in the Nether if there's a Wither Demon spawned anywhere on the map, the audio for it will be as if it's right in my ear no matter what. It doesn't appear to be taking any distance into account so now when there's multiple of them the audio stacks and continuously gets louder.

**Comment by mariumbacchus** [comment]
I'll look into it
