### ISSUE TITLE
bad render with this mod

### ISSUE THREAD

**Issue by VaporeonScripts** [mariumbacchus/Soulslike-Weaponry#106]
when i add this mod, it makes all rendering look low quality/grainy, if i remove it, it doesnt happen anymore, please fix it

**Comment by mariumbacchus** [comment]
Rendering of what? Blocks, entities or items? Do you have any special video settings on or a certain render distance? What version of the mod and minecraft are you playing? Can't fix anything if you're not specific enough.

**Comment by VaporeonScripts** [comment]
hi, thank you for replying, im using latest one, 1.20.4 with latest fabric api, with render i mean blocks or anything , idk how to explain but it makes all look grainy/pixel moving, only happens when i add ur mod.

**Comment by mariumbacchus** [comment]
Can you provide a side by side image comparison? With and without the mod.

**Comment by mariumbacchus** [comment]
It could also be another mod conflicting with shaders, or even the shaders themselves having issues with this mod.

**Comment by VaporeonScripts** [comment]
nah it does same with no shader too

**Comment by VaporeonScripts** [comment]
as said, its ur mod that causes me render issues.

**Comment by mariumbacchus** [comment]
Could you at least provide pictures side by side?

**Comment by VaporeonScripts** [comment]
its notable only in moving, or if something moves

**Comment by mariumbacchus** [comment]
Alright, provide video with and without the mod in, that would help out a lot.

**Comment by VaporeonScripts** [comment]
i will be able to record it like tomorrow

**Comment by NolanHewitt** [comment]
They did not record it

**Comment by mariumbacchus** [comment]
Seems like it. Will be closed soon if no video is provided.

**Comment by VaporeonScripts** [comment]
Mb,i forgot,i will record it today/tomorrow

**Comment by rohxu** [comment]
and he forgot again, it might be something on your side. I have no problems regarding rendering with and without shaders

**Comment by NolanHewitt** [comment]
Probably something on their end for sure. I have no issues like that either and I run a pretty big set of mods.

**Comment by mariumbacchus** [comment]
Glad to hear that, will close it now.
