### ISSUE TITLE
Fallen Icon's 2nd phase regeneration can be interrupted using Skofnung

### ISSUE THREAD

**Issue by Cirvel** [mariumbacchus/Soulslike-Weaponry#107]
[SW 1.1.2 [1.20.4]](https://modrinth.com/mod/mariums-soulslike-weaponry/version/1.1.2-1.20.4-fabric)

When the Fallen Icon enter its 2nd phase and starts healing, the player can prevent the boss from regenerating to full health by hitting it with a Skofnung (the only weapon I know that temporarily prevents healing to targets), this makes the 2nd phase fight shorter by lowering its starting health to around a half.

To take it further, if the last damage that starts the 2nd phase is from a Skofnung with Sharpness V, the effect can last longer than the entire healing process, essentially denying any regeneration at all and starts the boss with just a sliver of health.

**Comment by mariumbacchus** [comment]
That's an oversight, thanks for pointing it out. Will be fixed.
