### ISSUE TITLE
Game crashing during returning Knight boss battle

### ISSUE THREAD

**Issue by ImRonky** [mariumbacchus/Soulslike-Weaponry#111]
game is crashing and giving exit code 1 every time i try to kill returning knight, get him to about half health usually and game will crash. Fanstay MC fabric on cursedforge, log included
[hs_err_pid15188.log](https://github.com/mariumbacchus/Soulslike-Weaponry/files/14971536/hs_err_pid15188.log)

**Comment by NolanHewitt** [comment]
I've encountered this a good bit with this boss. Happened a lot at the start of the fight for me

**Comment by mariumbacchus** [comment]
Update java version and your drivers if you haven't already. If this doesn't help, and you've made sure to allocate enough ram to minecraft as well, then make a new issue post here if the crash persists. A video of you showing steps to reproduce the issue would also be nice.
