### ISSUE TITLE
Boss health changes in config not properly applying in game. 1.20.1

### ISSUE THREAD

**Issue by evade-dev** [mariumbacchus/Soulslike-Weaponry#112]
When configuring the bosses health in the provided config file. The maximum possible health of the bosses change, but the actual starting value stays the same. For example, if a bosses default HP value is 200 and I change it to 400 in the config. In game it will show 200/400 HP. I am using Mob Plaques to view health values. Below are images representing the issue as well as the mods and versions I am using as to observe this bug. I haven't tested this in particular, but it is possible the other values might not be changing anything either, such as damage modifier.

Minecraft 1.20.1

Related Mods:
Fabric 0.15.9 and Fabric 0.15.10 (happened to be trying both versions in setting up modpack)
soulslike-weaponry version 1.1.3 (and 1.1.2 had this issue, i updated to see if it was fixed)
fabric api version 0.92.1
geckolib 4.4.4
Forge Config API Port 8.0.0
AttributeFix 21.0.4

Unrelated Mods:
Mob Plaques 8.0.1
Puzzles Lib 8.1.18
Sodium 0.5.8
Sodium Extra 0.5.4
Reese's Sodium Options 1.7.2

Image examples of config and result in game. I am only showing the decaying king, but it happens with every single boss in this mod.

![decaying king cfg](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/144448407/13ac9bd2-2b6e-4977-84a2-cc7c3f4af66f)

![decaying king ingame](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/144448407/e4eb22ca-b041-4c43-90a9-dff5f298ce18)

**Comment by mariumbacchus** [comment]
If the boss spawned in/generated before the change in the config, then the health won't naturally change. New generated boss entities hopefully will. That's just how minecraft works when initializing entities. Tell me if this isn't the case.

**Comment by evade-dev** [comment]
This is occurring when generating new worlds. Apologies, I should have been more specific about that.

**Comment by mariumbacchus** [comment]
That's odd, for some reason the HP upon generating in a structure caps at 800, must be some mojang shenanigans. I'll look into a fix.

**Comment by evade-dev** [comment]
To clarify, this is occurring for every boss. So the Old Champions Remains for example won't even go above 200 HP. I just thought this might be relevant given your statement of 800 HP cap.

I'm not too skilled with programming so take this with a grain of salt, but from my own look at your code, the `getHealth` and `getMaxHealth` functions seem to be the only ones I can find relating to entity health values, so hopefully its not too complicated lol.

**Comment by mariumbacchus** [comment]
It is because when I made the structures and spawned the entities within them, they had their values set, and I guess they won't be updated once the structures spawn. I'll figure something out.

**Comment by younghun1945** [comment]
Has the content been fixed? I find the same bug in the same version and the same environment.

**Comment by mariumbacchus** [comment]
Fixed in the next upcoming update.
