### ISSUE TITLE
Respawning bosses??

### ISSUE THREAD

**Issue by Kmcgroovy** [mariumbacchus/Soulslike-Weaponry#113]
I’m on the fantasy mod pack and for the quest line I need to kill old champions remains but I had already beaten him before hand. Now I’m stuck and am looking for a way to respawn him so I can move forward with the quests

**Comment by Kmcgroovy** [comment]
And the brimstone Nectar item isn’t working

**Comment by mariumbacchus** [comment]
I have no idea what a "brimstone Nectar" item is, it is not a part of this mod. You can respawn bosses by right clicking the different altars with certain items. For Old Champion, right click Old Moon Altar with Draugr sword. Check the wiki out next time you have questions.
