### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'soulsweapons'!

### ISSUE THREAD

**Issue by LubbokXV** [mariumbacchus/Soulslike-Weaponry#114]
PLZ HELP!
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'soulsweapons'!

![image](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/167282934/c874909f-afac-4ef7-9b1d-8bd362ef44e7)

**Comment by mariumbacchus** [comment]
If it's the 1.20.4 version, then I forgot to change the fabric version needed in the fabric json file. What this means is that you need the newest fabric version, you are using an outdated one.
