### ISSUE TITLE
Darkin Scythe (Prime) Umbral Trespass ability

### ISSUE THREAD

**Issue by rohxu** [mariumbacchus/Soulslike-Weaponry#116]
Hey. I recently found the scythe and thought it looked cool. Then I wanted to see how I can use the Umbral Trespass ability and It just doesnt work. I used right click, shift right click, ability button and nothing works. Can't find anything online or on the wiki aswell.

**Comment by rohxu** [comment]
So is it a bug that the ability keybind doesnt work with the weapon? because it doesnt even say anything in the tooltip

**Comment by mariumbacchus** [comment]
You use it by right clicking, it will then target the last entity you attacked. If you aren't in combat then naturally nothing will happen.

**Comment by rohxu** [comment]
I see, weird. Idk it didnt work yesterday, even in combat, worked today though so i guess its fine.
