### ISSUE TITLE
Update 1.18.2 and 1.19.2 to 1.1.3

### ISSUE THREAD

**Issue by DoubL753** [mariumbacchus/Soulslike-Weaponry#120]
Hello ! I have seen in the 1.1.1 changelog that a bug have been fixed regarding boss particules (which was crashing my game before), but it doesn't have a 1.19.2 version... Is it possible to get the newest version in this version ?

**Comment by mariumbacchus** [comment]
Will update the older versions later, haven't bothered yet since they weren't as popular as the 1.20 version and takes a while to do.

**Comment by DoubL753** [comment]
Okay ! Thank you very much.

**Comment by mariumbacchus** [comment]
Uploaded 1.18.2 and 1.19.2 1.1.3 versions now, will be available for download shortly.

**Comment by DoubL753** [comment]
Thank you so much :D
