### ISSUE TITLE
3D Models of weapons cause items in inventory to not render

### ISSUE THREAD

**Issue by AbsoluteInDoubtX** [mariumbacchus/Soulslike-Weaponry#122]
When I have some of the weapons in my inventory (so far tested with Soul Reaper and Darkin Blade), many items stop rendering in my inventory/chests (seems to be blocks only but I'm not sure). This has to do with the 3D models because if I use the resource pack to convert them to 2D it stops happening. 

![image](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/170983858/342fd9db-578f-42f1-92f6-acf71379ea91)

**Comment by mariumbacchus** [comment]
This might be because of another mod having incompatibility issues. Maybe look into the other mods in your mod list and see if other ones are the culprit?

**Comment by slapjd** [comment]
I can confirm this appears to be an interaction between this mod and ImmediatelyFast's HUD batching.
Installing just this mod and ImmediatelyFast on fabric 1.20.1 causes the issue, but only in the hotbar (can be seen by having a chest and the comet spear in your hotbar, the chest will disappear).
Some other mod included within the Adrenaline (and by extension Additive) pack seems to spread this effect to inventory screens but removing ImmediatelyFast or disabling it's hud_batching setting fixes the problem in both situations.

**Comment by mariumbacchus** [comment]
Sounds like an issue on their part, most of my models either are made through geckolib or the normal item json format mojang provides. Many of the items may have a large number of cubes though, but I don't see how it would give this effect when combining with those mods when it works fine with any other. Maybe make an issue post on their end, as I don't have anything that modifies the hud of the player in the code (besides the posture meter which is it's own thing). I'm happy to help if there is something for me to solve though, so just make another issue if there is something I can do.
