### ISSUE TITLE
I translated into Japanese

### ISSUE THREAD

**Issue by Lqkuq** [mariumbacchus/Soulslike-Weaponry#123]
Hello, I decided to open an Issues since there was no mention of how to contribute.
This is what I did to play with my friends, but I think it would be beneficial to other players as well.
I can't guarantee that the translation is perfect, and some of it is left as is because I couldn't think of anything that would fit well into Japanese.

And if I think of a translation that fits, I'll probably make an update so it would be nice if you could let me know how to contribute.
Thank you!

[ja_jp.json](https://github.com/mariumbacchus/Soulslike-Weaponry/files/15492839/ja_jp.json)

**Comment by mariumbacchus** [comment]
Thank you for the effort! Normally you make a pull request so I can merge it into the main branch, but this works fine too. I'll implement this next update!

**Comment by Lqkuq** [comment]
Thanks for the reply, I will send a pull request when I make an update next time.
