### ISSUE TITLE
Frienzied Shade's Shadow & Moonlight attack instakills player, can't disable!

### ISSUE THREAD

**Issue by DarkFighter5000** [mariumbacchus/Soulslike-Weaponry#124]
I'm making an RPG modpack, many of the classes has weak armor like gold or leather (without protection) and the Frienzied Shade's Shadow & Moonlight attack instantly kills the players using that. I find it impossible to hide from it and I can't turn it off or change it in the config file either. I need a way to disable that attack or drastically reduce the damage it deals!

**Comment by mariumbacchus** [comment]
There is an attack damage modifier in the config for the Frenzied Shade, change it to a value lower than one to reduce it's damage. This will lower all of it's damage though.

Keep in mind that you can block the Moonlight beam it shoots out at you with a shield. The fights aren't supposed to be easy, but aren't meant to be fought with leather/gold armor either, so maybe it's best to lower the damage modifier in general through the config.
