### ISSUE TITLE
Major crashes

### ISSUE THREAD

**Issue by mining1221** [mariumbacchus/Soulslike-Weaponry#126]
When fighting the fallen icon and the chaos bosses i seem to be able to fight one whole boss and then crash when the icon loads his second phase after respawning him. But for chaos after killing one and the other becomes empowered it crashes. this happens every time on single player with out reason. I have tried everything i can think of lowering my render distance as low as i can, adding more memory to it. If you could please give any suggestions on how to fix it or see if its an issue with the mod, or if its a compatibility issue? Please let me know if there is any information you need.

**Comment by mariumbacchus** [comment]
It is a known issue, but crash logs are always appreciated.

**Comment by mining1221** [comment]
Ill track those down and upload them as soon as possible

**Comment by mining1221** [comment]
[crash-2024-05-05_21.23.53-client.txt](https://github.com/user-attachments/files/15753358/crash-2024-05-05_21.23.53-client.txt)
[crash-2024-06-08_01.09.49-client.txt](https://github.com/user-attachments/files/15753360/crash-2024-06-08_01.09.49-client.txt)
[crash-2024-06-08_01.11.51-server.txt](https://github.com/user-attachments/files/15753362/crash-2024-06-08_01.11.51-server.txt)
Should be those along with a few others but nothing changes between them

**Comment by mariumbacchus** [comment]
It doesn't seem like those are related to soulsweaponry, the first one is an issue regarding passangers (?), the second one is a sodium issue and the third has something to do with advancements. I don't know if soulsweaponry is related to those issues, maybe try to recreate the issue/crash and send that report?

**Comment by mining1221** [comment]
Those are the only ones i could find might be a issue with a mod rendering it then i do have a bunch of rendering things thanks anyways ill make a new issue if i can recreate it and its responsible
