### ISSUE TITLE
Crash due to particles?

### ISSUE THREAD

**Issue by Shiroo2157** [mariumbacchus/Soulslike-Weaponry#127]
App: Curseforge

Minecraft version: 1.20.1

modloader: Fabric 0.15.11

mod version/file: soulslike-weaponry-1.1.3-1.20-fabric.jar

dependencies: 
GeckoLib : 1.20.1-4.4.6
AttributeFix : 1.20.1-21.0.4
Fabric API : 0.92.2+1.20.1

other mods: none

Crash due to particles? from the bosses. Most notably the Returning Knight and the False Icon. Tested in their respective structures, and on a superflat world via spawn eggs.

Attached is the crash report.
[souls crash 6-11.txt](https://github.com/user-attachments/files/15793233/souls.crash.6-11.txt)

**Comment by mariumbacchus** [comment]
If you haven't already, update java and your drivers. If that doesn't help, and you're making sure you're allocating enough ram to minecraft as well, then make another issue post. A video of you showing steps to reproduce the crash would also be appreciated.
