### ISSUE TITLE
Crash from the nowhere

### ISSUE THREAD

**Issue by pedrikihacker** [mariumbacchus/Soulslike-Weaponry#128]
when i just open minecraft 1.18.2 forge with the soulslike weaponry mod, it CRASHES directly, i have geckolib in my mods folder, some explanation?

**Comment by mariumbacchus** [comment]
What is the output message?

**Comment by nekosenseinyan** [comment]
Hi! sorry, the same thing happened to me, the game is not launching and just says: Error, Game Crashed. exit code: 1

**Comment by creatinggamecheater** [comment]
same

**Comment by mariumbacchus** [comment]
Sorry for late response, an update will come soon that fixes these issues.
