### ISSUE TITLE
"This crash may be caused by an out of date driver" Returning Knight/Fallen Icon

### ISSUE THREAD

**Issue by RBLXUSER2008** [mariumbacchus/Soulslike-Weaponry#129]
![image](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/135447653/0ab68d4a-0ccd-4c84-bedc-1ed89fc643b3)

consistent crashing mostly around anything involving fireworks, disabling fireworks reduces it but it still occurs, mostly happens with fallen icon and the re-knight, upon crash bosses regain health/revert to a prev savestate strangely enough

vers is fabric 1.20.4

[log.txt](https://github.com/user-attachments/files/15858993/log.txt)

**Comment by mariumbacchus** [comment]
Update java version and your drivers if you haven't already. If this doesn't help, and you've made sure to allocate enough ram to minecraft as well, then make a new issue post here if the crash persists. A video of you showing steps to reproduce the issue would also be nice.
