### ISSUE TITLE
Crash when I use Chestplate's special ability "lych life" 

### ISSUE THREAD

**Issue by RidNeyy** [mariumbacchus/Soulslike-Weaponry#132]
Crash when I use Chestplate's special ability "lych life" and damage someone (sometimes crashes immediately after use)
Crash repot - [crash-2024-06-22_02.48.06-server.txt](https://github.com/user-attachments/files/15934618/crash-2024-06-22_02.48.06-server.txt)

**Comment by mariumbacchus** [comment]
Fixed for the upcoming update.
