### ISSUE TITLE
Freyr Sword doesn't come back on death

### ISSUE THREAD

**Issue by lilkura** [mariumbacchus/Soulslike-Weaponry#133]
Im currently using DarkRPG version 7.9.8. and as far as I'm aware when you die the Freyr sword is supposed to stay in your inventory or you can recall it. When I try to recall it, it says There is no Freyr sword bound to you. So I have to go wherever I died to pick it back up again. I'm not sure if this is what is supposed to happen or not.

**Comment by mariumbacchus** [comment]
It was never intended to go back to your inventory upon your death. If it was out as an entity when you died, then it will stay at your death location until right clicked to pick it up. If it was in your inventory, then it is dropped just like the rest of your items upon death.
