### ISSUE TITLE
crash "EXCEPTION_ACCESS_VIOLATION (0xc0000005)"

### ISSUE THREAD

**Issue by vred1** [mariumbacchus/Soulslike-Weaponry#135]
1.20.4 fabric

I reported the issue here, since I noticed that the mod is mentioned 3 times. The issue still persists after reinstalling java and updating the drivers.
this is mentioned 3 times in the logs:
`net.soulsweaponry.particles.ParticleHandler::particleOutburst`
line 30, 209, 523

These are the complete logs:
https://mclo.gs/jQybOy1

the issue might be actually related to https://github.com/mariumbacchus/Soulslike-Weaponry/issues/111 , since I was fighting the same boss and got a similar error.

**Comment by mariumbacchus** [comment]
If you haven't done so already, update your java version and your drivers. If this doesn't help, and you've made sure to allocate enough ram to minecraft as well, then make a new issue post here if the crash persists. A video of you showing steps to reproduce the issue would also be appreciated.
