### ISSUE TITLE
Comet spear is a bit broken

### ISSUE THREAD

**Issue by DoubL753** [mariumbacchus/Soulslike-Weaponry#136]
I am hosting an smp with many friends, and after 6 months in we finally discovered the potency of this weapon. I got a few complaint because the guy holding it went 600 blocs in the air before falling back down on the ground, effectively one shooting everyone and everything in our main community town, at spawn.

So I was wondering : is it possible to add the possibility in the configs to cap the damage, range and knockback of the item, to a certain degree, to balance the weapon a bit ? Because it's not possible to do yet...

**Comment by Emissivity** [comment]
I was having this same issue on my server so I made a fork that added a bunch of configuration, including changing scalars on the comet spear. Was just merged to this branch and should be available in the next update, whenever that's released.

**Comment by mariumbacchus** [comment]
For the next update I've added more config options for Calculated Fall and Ground Detonation events for all the weapons, namely:
- Cap on expansion
- Cap on damage
- Base expansion
- Expansion modifier
- Bonus damage from fall distance modifier
- Boolean for whether damage should heal the player
- Healing modifier based on damage dealt

Hope this helps.
