### ISSUE TITLE
Kraken Slayer model is not technically accurate

### ISSUE THREAD

**Issue by thatvia** [mariumbacchus/Soulslike-Weaponry#144]
Jinx is shown in [this image](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2F9gx4n7olpiy51.jpg%3Fwidth%3D1500%26format%3Dpjpg%26auto%3Dwebp%26s%3D3fc39bbee1d901b7592e25c5e5a11469975977fa) on the right side to be holding and fleeing with the Kraken Slayer, showing it to be a (potentially even ship mounted) harpoon gun used for fighting sea monsters. It's sleek and long to hold the entire harpoon.

Maybe something for a future update? Sorry if this sounds pedantic, I am very into the lore of these things. The other 3D models are great.
![image](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/172602888/5927d246-ed45-4abb-88cb-80f408634e32)

**Comment by thatvia** [comment]
Not sure how to add labels

**Comment by thatvia** [comment]
Also pictured, which have gotten obscure or no representation elsewhere, are Eclipse and Immortal Shieldbow among a few others.

**Comment by mariumbacchus** [comment]
Thanks for the image, it's nice to have something more to work with than just the ingame item icon. I'll make a change when I can.

**Comment by mariumbacchus** [comment]
Fixed for the next update.
