### ISSUE TITLE
Calculated Fall Effect with Featherlight

### ISSUE THREAD

**Issue by hansukeee** [mariumbacchus/Soulslike-Weaponry#145]
I'm new to using this mod and I got the Featherlight sword, and I need the Calculated Fall effect to perform the special attack with Featherlight. The Effects description of the wiki only tells me what the effect does, and not how to get it. Can anyone tell me how to get this effect for the attack?

**Comment by NolanHewitt** [comment]
Certain weapons such as the Comet Spear and Darkin Blade grant it when using their ability.

**Comment by mariumbacchus** [comment]
Only the Comet Spear and Darkin Blade gives you the effect. I'll add info to the wiki so this info is more accessible.
