### ISSUE TITLE
Darkmoon Bow can hit endermen

### ISSUE THREAD

**Issue by NolanHewitt** [mariumbacchus/Soulslike-Weaponry#146]
Maybe this is intentional, but I noticed that this bow can hit endermen both with its regular shots and the ability.

**Comment by mariumbacchus** [comment]
Was intentional originally, I'll add a config line for those who are opposed to this mechanic.
Edit: Nevermind, I'll keep in consistent with the other projectile immune bosses and make the Enderman immune too.

**Comment by NolanHewitt** [comment]
I believe it is still possible to hit enderman with the darkmoon bow.

**Comment by mariumbacchus** [comment]
Yes, a rework to make it compatible with projectile damage attribute and ranged weapon api made it work on enderman again, but I feel like I will keep this in.
