### ISSUE TITLE
1.18.2 Forge Crashes on Opening Game FORGE VERSION: 40.2.0

### ISSUE THREAD

**Issue by ahhwaa** [mariumbacchus/Soulslike-Weaponry#147]
Just Marium's and GeckoLib in the mods folder, Minecraft version: 1.18.2 FORGE. Forge Version: 40.2.0

[latest.log](https://github.com/user-attachments/files/16369184/latest.log)

**Comment by ahhwaa** [comment]
added AttributeFix and still not working

**Comment by mariumbacchus** [comment]
Sorry about that, it is a known issue and I'm working on an update that fixes this.
