### ISSUE TITLE
Forlorn spawn conditions ?

### ISSUE THREAD

**Issue by notNIKITAzed** [mariumbacchus/Soulslike-Weaponry#148]
I'm playing the Prominence 2 modpack and have been running around the soul sand valley for quite a while trying to get their armor but haven't even seen one, would you be able to share their actual spawn conditions ? like the crimson demons are specifically on crimson nylium which was helpful to know. 

just so I know if I'm doing something wrong or am very unlucky.

**Comment by Buckachicka** [comment]
I've got the same issue. either its bugged or the spawn rate is way too low for average armor

**Comment by Buckachicka** [comment]
I figured it out. Invading forlorn i think is just random luck ive found found in the last 2 hours. but you can use the soul reaper scythe and kill mobs with it. then u can right click around every 10 mobs and it will spawn a forlorn. it will drop at least the boots and helm and the scythe of Forlorn and the heap of raw iron sword. yet to get chest plate or leggings but will probably come in time

**Comment by Buckachicka** [comment]
yep they drop everything. just kill around 10 mobs with the scythe then you can spawn a forlorn.

**Comment by mariumbacchus** [comment]
My bad, I totally forgot to change the wiki about the fact that it spawns in the Nether Wastes biome. The spawn weight is also very low and it will only spawn alone too. I'm going to change it so that it spawns everywhere in the Nether and maybe increase the spawn weight too.
