### ISSUE TITLE
[BUG] More of a question

### ISSUE THREAD

**Issue by Dumpling00** [mariumbacchus/Soulslike-Weaponry#149]
Fabric, 1.20.1, Latest available version of Soulslike on Modrinth, - I am currently working on a progression-based datapack and I needed to change some recipes in order to make Marium's weapons something a bit harder to obtain, but when I go into the jar, there are certain recipes missing, namely some of the more advanced weapons and the silver bullets.

![image](https://github.com/user-attachments/assets/f476d9ff-43c5-44af-95f7-5d35b34729a3)

These are the recipes appearing, but yeah, all of these (from bloodthirster onward, excluding armor and the last two items in the list) have no recipe available in the file, yet the recipe still shows up in JEI, so they are indeed craftable, but without a json, these recipes cannot be overridden.

Help, please?
![image](https://github.com/user-attachments/assets/df1e8900-f90c-40f7-9f52-7ded96931cc3)

**Comment by mariumbacchus** [comment]
The newest live version (1.1.3) has all the recipes hardcoded in the code, but I have already changed this to be in json format for the upcoming update. The update will release once I'm done with most of the issue posts here on github.

**Comment by Dumpling00** [comment]
Thank you! Looking forward to it.
