### ISSUE TITLE
[FEATURE] Better integration with WorldGen mods?

### ISSUE THREAD

**Issue by Dumpling00** [mariumbacchus/Soulslike-Weaponry#150]
I use Terralith and Tectonic, along with Terrablender, Biomes you've gone and Larion, granted this might be very situational, but was wondering if there's any change for better structure blending?

https://github.com/user-attachments/assets/3458eb7f-bb36-4bbd-997f-a51cccd2d735

**Comment by mariumbacchus** [comment]
All structures are made with the datapack/json format mojang introduced a while ago, so I don't really have a lot of control on how they spawn. I'll check the respective mods to see if there is anything I can do.

**Comment by mariumbacchus** [comment]
Couldn't find anything to fix the issue since the structures are made of datapacks, maybe ask the devs of Terralith? Make a new issue post if there is something I can fix.
