### ISSUE TITLE
[FEATURE] Make Dependencies clear in the mod's Modrinth page.

### ISSUE THREAD

**Issue by CorvidArekusu** [mariumbacchus/Soulslike-Weaponry#151]
Tried to install the mod, didn't know about any dependencies since none are mentioned in the mod's Description tab.
Adding a brief section that says something like "Dependencies: Geckolib | Attributefix" or something it would be perfect. Short, simple, helpful.

**Comment by mariumbacchus** [comment]
If you click on any version there is a "Dependencies" overview if you scroll down, but yeah sure I can also write it on the page itself.
![image](https://github.com/user-attachments/assets/757be7e3-7c7c-443e-8a1c-ddf9d82c55b5)
