### ISSUE TITLE
[BUG] Game crashes when Returning knight, Fallen Icon, or any of the deities use their attacks.

### ISSUE THREAD

**Issue by NoRestForWicked** [mariumbacchus/Soulslike-Weaponry#152]
**Minecraft, modloader and mod versions**

Minecraft: 1.20.1
Fabric: 0.15.11
Soulslike-Weaponry: 1.1.3

When fighting a boss such as the Night Prowler/Day stalker (The bug happens EVERYTIME I fight them), Some of their attacks just CRASH the game. No freeze. Just crash.

1. Summon the deities
2. Have them use their attacks
3. See error

I do not think that it should crash when you fight the bosses, but it is quite often in the deity fight.

I do have other mods installed, but I isolated the mod and tried it and it still crashes.

**Comment by mariumbacchus** [comment]
A crash log would be appreciated.

**Comment by NoRestForWicked** [comment]
[latest.log](https://github.com/user-attachments/files/16489191/latest.log)

I did some more testing, and I noticed a correlation

I was able to kill it twice before crashing on the third attempt. The only difference was that the third attempt was directly after I loaded chunks other than spawn chunks. I have no clue what it may mean, it may be chance but I just thought I should note that.

**Comment by NoRestForWicked** [comment]
Another thing to note is that this crash also happens sometimes when using the comet spear and nightfall abilities

**Comment by mariumbacchus** [comment]
That log does not contain info about the crash. I also just uploaded a new update, check if the crash still happens in that one (1.1.4.1).

**Comment by NoRestForWicked** [comment]
The new update makes it less prominent I think, I've noticed that so far. But I will upload a new log on a singleplayer showcasing the crash (it still happens)

**Comment by NoRestForWicked** [comment]
[latest.log](https://github.com/user-attachments/files/16499823/latest.log)
From singleplayer

**Comment by NoRestForWicked** [comment]
The exit code was 1

**Comment by mariumbacchus** [comment]
Really odd, I still see no indication of a crash in the log, only loading mods and all that. Does it still happen if you isolate the mod? Maybe try to allocate another gig ram and see if that helps, often times exit code 1 means you ran out of memory or a driver is outdated.

**Comment by NoRestForWicked** [comment]
I will try it but I am confused as to why it may happen

**Comment by mariumbacchus** [comment]
I have no idea either since I never seem to crash while testing myself.

**Comment by NoRestForWicked** [comment]
It has somethin to do with particles I assume
In multiplayer when fighting bosses or using certain weapons like nightfall, the game will crash for players and players ONLY. The server never crashes and has 8 gigs ram allocated (my personal client has 10 gigs allocated)

**Comment by NoRestForWicked** [comment]
It could be mod conflict

**Comment by NoRestForWicked** [comment]
but I promise it happened even when the mod was isolated last update

**Comment by mariumbacchus** [comment]
I knew it was an issue last patch, but I was hoping I fixed it with this one. See if you could get a hold of the server crash log or something. I'll look into it for a possible fix.

**Comment by NoRestForWicked** [comment]
it seems to be a mod conflict, but Im not sure which mod
it reverts the world back to when I logged on b4 the crash, like if it never happened

**Comment by mariumbacchus** [comment]
Oh really? Figured out which one?

**Comment by NoRestForWicked** [comment]
I have not, but by itself I was able to kill the boss 3 times without issue

**Comment by NoRestForWicked** [comment]
I am going to make a new thread showcasing a good bit of bugs with the darkin scythe, and also the crash from my pov

**Comment by NoRestForWicked** [comment]
hey, if you don't mind me asking on a rough eta on the patch, that would be great.
Also, A quick small bug I thought I'd share is that if you hold down rightclick with nightfall, then use its leftALT ability, then release right click you can essentially use both the smash and defensive abilities at the same time.

**Comment by mariumbacchus** [comment]
The more bugs that pop up, the more delayed it gets since it means more work. I also have to update all 5 versions with the patches so it naturally takes time.

**Comment by NoRestForWicked** [comment]
Oh, I am sorry lol. But I am glad I can help fix even the little stuff :D (sorry for all the work)

**Comment by mariumbacchus** [comment]
No problem, it is only a matter of time before they get found by others and fixing them is inevitable. Thanks for finding them and bringing it up.

**Comment by mariumbacchus** [comment]
I've just uploaded the patch now, will take a few minutes before the CurseForge team approves it. I will close this issue since I hope it no longer happens, open another if it still occurs.
