### ISSUE TITLE
[BUG] Darkmoon Bow doesn't shoot in 1.1.4.1 (MC 1.20.1 Fabric)

### ISSUE THREAD

**Issue by NolanHewitt** [mariumbacchus/Soulslike-Weaponry#153]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Fabric: 0.15.9
Soulslike-Weaponry: 1.1.4.1

**Describe the bug**
When firing the darkmoon bow regularly, no arrow is shot. The alt fire still works like normal. In 1.1.3 the bow can show its regular shot just fine.

https://github.com/user-attachments/assets/13eb9936-6edb-4fea-b402-01191cea1f39

**Comment by mariumbacchus** [comment]
Does this still happen with and without other mods installed? (Excluding dependencies)

**Comment by mariumbacchus** [comment]
Just tested it myself and it seems to work fine on my end. I am guessing there is another mod causing this conflict. If you could figure out which one, see if there is a config for it to blacklist or whitelist items to make them not affect this mods' items.

**Comment by NolanHewitt** [comment]
I found the mod causing it, it's the mod [better multishot](https://modrinth.com/mod/bettermultishot), which is odd because that mod should only effect the multishot enchantment which is only on crossbows. It does have an option in the config to allow bows to use multishot (so not just crossbows) but I had that disabled. Testing it again with just Souls Weapons, Better Multishot, and the requirements to use each, this issue does occur on 1.1.4.1 but not in 1.1.3 for some reason.

I did try messing with the other config options for better multishot but none of them seem to fix the issue. I made an issue on the better multishot page as well as I'm not sure where the source of this bug is.

**Comment by mariumbacchus** [comment]
In 1.1.3 I completely overrode the bow and crossbow classes so no other mod had any effect on the custom ranged weapons. This naturally caused incompatibility issues with other mods, so now they act like normal bows and crossbows in 1.1.4.1. 
Does this issue happen to all the bows or only the Darkmoon Longbow? Does it happen to Galeforce and Kraken Slayer (both crossbow and bow version)?

**Comment by NolanHewitt** [comment]
I just took a look, the kraken slayer crossbow and krakens slayer bow work just fine. The galeforce is unable to shoot regularly, but its alt fire does still shoot an arrow interestingly.

**Comment by mariumbacchus** [comment]
But does the custom 3rd shot work on Kraken Slayer bow and crossbow then? I am guessing there is something with that mod which messes with either the entities or how the crossbow or bows get their arrow entity from. All bows and crossbows create an arrow entity, my custom bows override this arrow entity they get before it is returned to return a custom one.

**Comment by NolanHewitt** [comment]
So I gave that a try, the custom third shot from the kraken slayer bow doesn't work. Interestingly though, the custom third shot from the kraken slayer crossbow DOES work, dealing its bonus damage and looking different.

**Comment by mariumbacchus** [comment]
I will close this since it seems to be an issue with the other mod, reopen it or make a new one if there is something I could do.
