### ISSUE TITLE
[FEATURE]The ability to to add loyalty to Mjolnir and The Leviathan axe

### ISSUE THREAD

**Issue by NoRestForWicked** [mariumbacchus/Soulslike-Weaponry#155]
It sucks when other players pick up either the mjolnir or leviathan axe after I throw it at them and don't call it back in time

You should be able to enchant either weapon with Loyalty and that should keep them from being picked up by other players (enabled/disabled by config)

You could also just add a config stating whether the weapons can be picked up by other players or not even without loyalty.

:D

**Comment by mariumbacchus** [comment]
Oh that's a bug actually, other players shouldn't be allowed to pick up your axe/hammer. Will be fixed.

**Comment by NoRestForWicked** [comment]
Oh good, ty :D

**Comment by mariumbacchus** [comment]
Is now fixed for the next patch.
