### ISSUE TITLE
[BUG] Datapack doesn't replace recipes still

### ISSUE THREAD

**Issue by Dumpling00** [mariumbacchus/Soulslike-Weaponry#157]
Hi there! Was very excited to get the recipes be data driven again, but seems like something was left behind?
When replacing recipes via datapack - in this case the bloodthirster, the old recipes and crafting methos still remains.

Am I doing something wrong?

![image](https://github.com/user-attachments/assets/c7645c96-2d04-4b11-97c1-94cc71c4f872)

**Comment by mariumbacchus** [comment]
They were included and they work fine on my end, so yes there may be something you are doing wrong. Remember that the id of my mod is "soulsweapons", so to replace recipes you have to make a "soulsweapons" folder in the data folder, followed by "recipes" folder and then the id of the item, here being "bloodthirster". If you then put that datapack in the datapacks fodler in your world save and use /reload ingame, then the recipe should be overwritten.
