### ISSUE TITLE
[BUG]Leviathan Axe throw does not inflict permafrost

### ISSUE THREAD

**Issue by NoRestForWicked** [mariumbacchus/Soulslike-Weaponry#159]
Example:
Minecraft: 1.20.1
Fabric: 0.15.11
Soulslike-Weaponry: 1.1.4.1

Throwing the leviathan axe will not inflict permafrost onto entities

Throw the leviathan axe at any mob

Axe throw should permafrost mobs hit

**Comment by NoRestForWicked** [comment]
Yo just on a side note I found the coolest easter egg when using both Mjolnir and Leviathan axe and I'm telling you that was the coolest thing ever lmao :D

**Comment by mariumbacchus** [comment]
Glad you liked it, is the issue a consistent thing or just at some random times? Since it all works fine on my end.

**Comment by NoRestForWicked** [comment]
It is consistent, and by permafrost I mean the effect, not the cool explosion thing it does when it hits an entity

**Comment by NoRestForWicked** [comment]
Update: It works when you recall it, but not when you throw it initially.

**Comment by mariumbacchus** [comment]
Do you see particles on the mob when you hit it? Not the explosion ones, but rather snow particles or potion effect ones?

**Comment by NoRestForWicked** [comment]
I do not, and when tested with other players it does show potion particles or effect them with the effect, it only deals the damage from the initially throw hit

**Comment by mariumbacchus** [comment]
Nevermind, I found an inconsistency in the code where the explosion is supposed to give the effect, but sometimes it overlooks the entity hit. Has been fixed.
