### ISSUE TITLE
Incompatibilities with shielding 

### ISSUE THREAD

**Issue by DoubL753** [mariumbacchus/Soulslike-Weaponry#160]
Because most weapons of this mod use abilities with right click, you can't use a shield along with them.
Is there a way to change that ? For example, a key to enable/disable weapons abilities ?

**Comment by mariumbacchus** [comment]
Sadly, this is a feature integrated into minecraft where it prioritizes the main hand item over the shield, like with a bow or trident, trying to use the shield will result in charging the bow or trident. There is a config line to disable the usage of the weapon. However, this also disables all other passive abilities too, like the life steal passive on Darkin Blade being disabled with the right click ability.

**Comment by mariumbacchus** [comment]
I have made a config line "prioritize_off_hand_shield_over_weapon" that is set to false by default, this change will be up in the next patch.
