### ISSUE TITLE
How much experience is gained from each boss? (QUESTION)

### ISSUE THREAD

**Issue by VanishJr** [mariumbacchus/Soulslike-Weaponry#161]
**How much experience is gained from each boss? (QUESTION)**

Good afternoon, 

Unfortunately the wiki does not show how much experience is given when killing experience.  And in the mod files, also does not show the amount of experience for the boss. I would like to know how much experience I get from each boss.

In addition, I would suggest to write this information in the README file to make life easier for the user.

Thank you for your attention!

**Comment by mariumbacchus** [comment]
The xp drops can be changed in the config file for each boss. I will update the wiki with the information.

**Comment by NoRestForWicked** [comment]
the original xp drops are listed in the config anyways right?

**Comment by mariumbacchus** [comment]
Yep

**Comment by VanishJr** [comment]
Thx
