### ISSUE TITLE
[FEATURE] Ability to shield parry with other mod's shields?

### ISSUE THREAD

**Issue by NolanHewitt** [mariumbacchus/Soulslike-Weaponry#164]
I believe this mod checks for instances of ShieldItem to determine which items can shield parry, but items made using [Fabric Shield Lib](https://modrinth.com/mod/fabricshieldlib) are not this. An example being the shields from [Botania Combat.](https://modrinth.com/mod/botaniacombat) Would it be possible to instead check for the c:shields tag, and allow shield parrying with items with that tag?

**Comment by NolanHewitt** [comment]
Nevermind it looks like some mod shields can, its just one mod in particular that can't use it. I'll check with that mod first.

**Comment by mariumbacchus** [comment]
Absolutely, will implement this.

**Comment by NolanHewitt** [comment]
Thank you!

**Comment by mariumbacchus** [comment]
Fixed for next update.
