### ISSUE TITLE
[FEATURE] Geckolib

### ISSUE THREAD

**Issue by Sebaspc97** [mariumbacchus/Soulslike-Weaponry#168]
If a fabric mod needs geckolib then I cant use a forge mod that needs it aswell because I cant run both geckolib for fabric and forge.

I don't know if I am missing something but it would be great if this gets fixed.

**Comment by NoRestForWicked** [comment]
as far as I am aware, you cannot use forge and fabric simultaneously in the first place, if that is what you are referring to. If I misunderstood the question please correct me 
:D

**Comment by mariumbacchus** [comment]
This is why I am working on a forge port for the other versions too to avoid this issue with Sinytra connector (I am guessing you are referring to that). I will come when it is finished.

**Comment by MistifyedOne** [comment]
sorry if this is annoying, but is there any general ETA?

**Comment by Mqony** [comment]
@mariumbacchus  sorry if this is annoying, but is there any general ETA?
