### ISSUE TITLE
[BUG] Moonknight Particle bug EXCEPTION_ACCESS_VIOLATION (0xc0000005) 

### ISSUE THREAD

**Issue by Yrythaela** [mariumbacchus/Soulslike-Weaponry#170]
**Minecraft, modloader and mod versions**
Minecraft: 1.20.1
Fabric: 0.15.9
Soulslike-Weaponry: SW 1.1.4.2 [1.20.1] 

**Describe the bug**
Moonknight particle bug crashes the game client side but does not impact the server if within the range of Moonknight.

**Add logs**
[message (3).txt](https://github.com/user-attachments/files/16662368/message.3.txt)

**To Reproduce**
1. Summon Moonknight, enter phase 2
2. Wait for Moonknight to do an unknown specific move that summons the particles according to the crash log attached above
3. Crash the game due to EXCEPTION_ACCESS_VIOLATION (0xc0000005) 

**Expected behavior**
Fighting the Moonknight won't crash.

**Other mods or relevant info**
Using All of Fabric 7 modpack as a base
Spell Engine, RPG Series

**Comment by NoRestForWicked** [comment]
when the crash occurs, does it happen instantaneously? Like no lag it just *boom* crash?

**Comment by Yrythaela** [comment]
Just boom crash. No lag or anything. Program straight up just crashes. 

This is a problem that I encountered since I'm using Curseforge to use Marium's Soulslike for one of the modpacks. I think it might be helpful to put in the mod's description that this mod isn't compatible for Curseforge, specifically for 1.20.1 (not sure about other versions) due to Curseforge being stuck in an old Java version and being unable to change Java version.

I installed Prism Launcher and forced the launcher to use the the very latest version of Java 17.0.11 and suddenly the bug disappeared and the fight is completely fine.

**Comment by WarlockGonka** [comment]
I'm having the same problem with the Night Prowler when she does the attack with the scythes on the ground. It looks like to be a bug with the particles from the mod.

**Comment by NoRestForWicked** [comment]
It's an issue with the particles overloading the client with packets, which crashes the game. It's really inconsistent but happens to anything that uses/summons particles for the attack. Any boss or legendary that has an attack with particles has a chance to crash your game.

Yrythaela, you mention that prism launcher fixes the issue, correct? If you wouldn't mind further testing it with multiple fights that would be great. For me it's usually about 1/3 boss fights crash my game and I've noticed this number usually depends on how many chunks I have loaded. The more I have loaded the more often I crash when a legendary ability or attack is used or when a boss attacks.

**Comment by mariumbacchus** [comment]
> I installed Prism Launcher and forced the launcher to use the the very latest version of Java 17.0.11 and suddenly the bug disappeared and the fight is completely fine.

This is interesting. I am using java 17 in development and this may explain why I never get this crash. Forcing a newer version might fix it, but I am still not 100% sure. If any of you could test this out to a further extent that would be appreciated.

**Comment by mariumbacchus** [comment]
I will close this since it is the same issue as [this one](https://github.com/mariumbacchus/Soulslike-Weaponry/issues/162).
