### ISSUE TITLE
[FEATURE]Compatibility with backslot mod 

### ISSUE THREAD

**Issue by NoRestForWicked** [mariumbacchus/Soulslike-Weaponry#171]
**Is your feature request related to a problem? Please describe.**
The textures of the legendaries don't work correctly with the backslot mod for fabric 1.20.1 

**Describe the solution you'd like**
a texture compatibility fix

**Additional context**
link to backslot mod: https://www.curseforge.com/minecraft/mc-mods/backslot

**Comment by mariumbacchus** [comment]
Fixed for upcoming update.
