### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alarmgoose** [mariumbacchus/Soulslike-Weaponry#173]
I mentioned this in another post but I figure it would be best to make its own topic. Getting this crash with the newest forge version of the mod. Seems to be a issue with Better End since once I removed better end the mod works fine.

[crash-2024-08-23_22.48.08-client.txt](https://github.com/user-attachments/files/16734987/crash-2024-08-23_22.48.08-client.txt)

**Comment by mariumbacchus** [comment]
Just released a patch (1.1.4.4c) that hopefully fixes this issue, try with that one and tell me if it still occurs.

**Comment by alarmgoose** [comment]
> Just released a patch (1.1.4.4c) that hopefully fixes this issue, try with that one and tell me if it still occurs.

Just tested it out and everything is working fine with Better End! Thank you. I'll be sure to report any other bugs that hopefully do not pop up.
