### ISSUE TITLE
[BUG] 1.20.1 version of this mod has way too high forge version requirements

### ISSUE THREAD

**Issue by oof100200** [mariumbacchus/Soulslike-Weaponry#174]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
neoforge: 47.1.105
Soulslike-Weaponry: 1.1.4.4a

**Describe the bug**
can you change the version requirements to 47.1? because the currect forge version required of this mod, makes it unable to run on neoforge.

**Add logs**
[A log of the incident, i.e crash log if a crash happened or a log giving other warnings before the issue occured if necessary.](https://pastebin.com/mZAGXSca)

**Comment by mariumbacchus** [comment]
Sure, downgraded it now and will upload a small patch shortly.

**Comment by oof100200** [comment]
> Sure, downgraded it now and will upload a small patch shortly.

thanks
