### ISSUE TITLE
[BUG] Darkmoon longbow and Archer's RPG

### ISSUE THREAD

**Issue by car45167** [mariumbacchus/Soulslike-Weaponry#175]
Minecraft: 1.20.1
Forge: 47.3.1
Soulslike-Weaponry: 1.1.4.4a

Hi i tried to use the mod on forge while also having the ranger RPG mod with synitra connector and pufferfish . I was able to use the Archer's skill with the darkmoon longbow but i noticed that by leveling up (in pufferfish) the damage didn't increase when using the skills but only when firing normally.

pufferfish version 0.13.2

**Comment by mariumbacchus** [comment]
I'm not sure how Pufferfish implements it's damage bonuses to projectiles, but I'll look into it.

**Comment by car45167** [comment]
thank you

**Comment by mariumbacchus** [comment]
Fixed for next update.
