### ISSUE TITLE
[BUG] Game crashes on startup because of MSW

### ISSUE THREAD

**Issue by KiraKayn** [mariumbacchus/Soulslike-Weaponry#176]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Forge: 47.3.7
Soulslike-Weaponry: 1.1.4.4a

**Describe the bug**
With MSW installed minecraft crashes on startup, just like that

**Add logs**
[crash-2024-08-24_13.39.21-client.txt](https://github.com/user-attachments/files/16736421/crash-2024-08-24_13.39.21-client.txt)

**To Reproduce**
1. Simply launch minecraft'

**Expected behavior**
Expected minecraft to launch normally, but it crashed instead

**Other mods or relevant info**
The crash report mentioned Sinytra Connector and Better End, unsure if its related or not.

**Comment by mariumbacchus** [comment]
There are known issues with sinytra connector, so it is definitely related to that, but why would you use it? Are you trying to make it work with something like NeoForge?

**Comment by mariumbacchus** [comment]
So I just released a patch (1.1.4.4c) that hopefully fixes this issue. Try with that one and tell me if it still occurs.

**Comment by KiraKayn** [comment]
Yep, that fixed it, thank you so much man! Is the forge version fully complete now? Like, is it stable and has all the content the fabric version has?

**Comment by mariumbacchus** [comment]
It has all the content, but a bug with the Soulmass missing it's texture snuck through, so I've fixed that in the latest patch (1.1.4.4d, which is hopefully the last).
