### ISSUE TITLE
[BUG] Soulmass has missing texture, Its pure black

### ISSUE THREAD

**Issue by KiraKayn** [mariumbacchus/Soulslike-Weaponry#178]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Forge: 47.3.7
Soulslike-Weaponry: 1.1.4.4c

**Describe the bug**
The soulmass mob when summoned has a texture thats pure black for some reason

**Add logs**
I dont think it will help, but sure:  [latest.log](https://github.com/user-attachments/files/16737755/latest.log)

**To Reproduce**
Simply grab his spawn egg, and summon it.

**Screenshots and videos**
![kép_2024-08-24_211916225](https://github.com/user-attachments/assets/179cd2f9-a627-4f5b-b506-b68eb242e8e1)

**Comment by mariumbacchus** [comment]
Thanks for pointing it out, fixed in the latest patch.
