### ISSUE TITLE
[BUG] Epic Fight mod prevents use some of weapons abilities

### ISSUE THREAD

**Issue by GLMaster19** [mariumbacchus/Soulslike-Weaponry#179]
**Minecraft, modloader and mod versions**

Minecraft: 1.20.1
Forge: 47.3.5
Soulslike-Weaponry: 1.1.4.4d

**Describe the bug**
Hello there!
So, have a problem with some weapons. I can't use their RMB, like a Leviathan throw or Mjolnir throw. Have Epic Fight, maybe it is causing a problem?

**To Reproduce**
1. Download the latest Marium's Soulslike Weaponry for 1.20.1
2. Download Epic Fight 20.8.10.
3. Go to your world and try to use weapons RMB (not just Leviathan or Mjolnir)

**Screenshots and videos**
Video is down there.

https://github.com/user-attachments/assets/2fb3559e-0cde-4881-b424-4c3e2f2d175f

https://github.com/user-attachments/assets/f613801d-ee52-4051-8684-1954cf83b007

**Other mods or relevant info**
I have:
Epic Fight.
Weapons of Miracles.
Alex Mobs and Alex Caves (there is some weapons that have abilities).

**Comment by GLMaster19** [comment]
To be honest, I have a bigger amount of mods than those that I write down there. Also, there is a Sinytra Connector with Better End and Nether.
Maybe there is some incompability with them, don't rly know.

**Comment by mariumbacchus** [comment]
It is most likely Epic Fight mod messing with things again. It works in 1.18.2, but the newer versions likely does things differently and breaks stuff yet again.

**Comment by GLMaster19** [comment]
> It is most likely Epic Fight mod messing with things again. It works in 1.18.2, but the newer versions likely does things differently and breaks stuff yet again.

Yeah, I think you're right. The Epic Fight code has changed a lot, so there may well be conflicts. It's quite possible that the problem is with the block skills that activate on RMB. Could it be that they have a much higher priority than the abilities in your mod?

Also, maybe I can try to rebind somehow skills on RMB to another button?

**Comment by mariumbacchus** [comment]
I already made an issue post on their end requesting to blacklist items or another fix so that other weapons don't get their right click abilities overwritten. They hardcoded it pretty good so it's hard to get through.

**Comment by mariumbacchus** [comment]
Fixed for next update.
