### ISSUE TITLE
Do you need to put some translation work on crowdin?

### ISSUE THREAD

**Issue by DSRoie** [mariumbacchus/Soulslike-Weaponry#18]
To complete some Chinese translations...or other languages?
I'm sure many people are willing to help

**Comment by mariumbacchus** [comment]
Anyone can help update the language files. Not too long ago someone made a pull request to update the Russian language file. I sadly don't know Chinese, so it is up to others if they want to help.

**Comment by mariumbacchus** [comment]
Looks good, thanks for your contribution!
