### ISSUE TITLE
[FEATURE] Ability to disable/enable the unbreaking enchant making cooldowns faster

### ISSUE THREAD

**Issue by NoRestForWicked** [mariumbacchus/Soulslike-Weaponry#180]
**Is your feature request related to a problem? Please describe.**
Certain weapons such as darkin blade/nightfall have much shorter cooldowns when enchanted with unbreaking

**Describe the solution you'd like**
A config to disable unbreaking making cooldowns shorter

**Describe alternatives you've considered**
It would be very cool :DD

**Comment by mariumbacchus** [comment]
Alright will do.

**Comment by mariumbacchus** [comment]
Pushed the implementation now, will be up next update. Also added a minimum cooldown for weapons so items with illegal enchants (like unbreaking 10) won't break things. Added scaling to items that didn't have it before which is disabled by default in the config.
