### ISSUE TITLE
[BUG] Big Chungus Music Disc is prematurely cut off ~5 seconds into playing, Forge 1.20.1

### ISSUE THREAD

**Issue by seefourr** [mariumbacchus/Soulslike-Weaponry#182]
**Minecraft, modloader and mod versions**
Minecraft: 1.20.1
Forge: 47.3.7
Soulslike-Weaponry: 1.1.4.4d

**Describe the bug**
Big Chungus disc plays for a bit before cutting off

**To Reproduce**
1. Obtain jukebox and Big Chungus music disc
2. Try and play Big Chungus disc
3. Big Chungus disc plays, but cuts off after a short amount of time :(

**Expected behavior**
Big Chungus disc plays in full :)))

**Other mods or relevant info**
Tested in isolation with only soulslike weapons and its dependencies, issue still occured

**Comment by mariumbacchus** [comment]
Fixed for next update.
