### ISSUE TITLE
[BUG] Crash with Night Prowler EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by WarlockGonka** [mariumbacchus/Soulslike-Weaponry#183]
Minecraft: 1.20.1
Forge: 47.3.0
Soulslike-Weaponry: 1.1.4.4d

**Describe the bug**
when the Night Prowler makes a movement where it spins and hits the scythes on the ground, the game crashes 
**Add logs**
https://mclo.gs/QJrEYjn

**To Reproduce**
1. Summon the Night Prowler
2. Make she fight any boss from other mod
3. See error

**Other mods or relevant info**
I'm using MordernFix, FerriteCore and Embeddium for performance. Alongside with Epic FIght, L's ender Cataclysm and Mowzie Mobs.

**Comment by mariumbacchus** [comment]
Referring to [this](https://github.com/mariumbacchus/Soulslike-Weaponry/issues/170#issuecomment-2324968783) message, could you try to force minecraft to use Java version 17.0.11 and see if this fixes the problem?

**Comment by mariumbacchus** [comment]
Thanks to Wicked's testing, the easy fix is to update to java 17.0.11 or above. I will still try to figure out a fix for those who still have an outdated java version and don't know how to update.

**Comment by WarlockGonka** [comment]
Yeah, I tested it for 1 hour with other mods, fighting her, making she fights other bosses and everything went well when I used the java 17.0.11. But using java 21 the error still occurs
I'm gonna close this bug report and let this talk continue on #170  bug report
