### ISSUE TITLE
[FEATURE] Add ores to forge ores tag

### ISSUE THREAD

**Issue by seefourr** [mariumbacchus/Soulslike-Weaponry#188]
**Is your feature request related to a problem? Please describe.**
Allows simple integration with a some mods especially vein mining ones. No exact issues caused by them not being in the tag but there are benefits to having them in it

**Describe the solution you'd like**
Ore blocks from the mod are added to forge/ores tag

**Comment by mariumbacchus** [comment]
Thanks for the reminder, will do.

**Comment by mariumbacchus** [comment]
Fixed for next update.
