### ISSUE TITLE
[BUG] Calculated Fall Launch Height

### ISSUE THREAD

**Issue by NolanHewitt** [mariumbacchus/Soulslike-Weaponry#189]
Is calculated fall supposed to launch mobs this high? I haven't made use of the effect for a while so I'm not sure if this is how its always been, but this seems really high for this height. If I go much higher than this they get launched into orbit and wont come back down.

https://github.com/user-attachments/assets/79721710-d03d-4a96-87f3-98fd88c0e9f3

**Comment by mariumbacchus** [comment]
I agree that it's a bit much, I must've forgot to change the values properly when changing how it is calculated from the config. You can change the values yourself in the config if you feel like it for now, I will change this next update.

**Comment by NoRestForWicked** [comment]
see this is hilarious but yeah we disabled the launch height (set multiplier to 0) lol

**Comment by mariumbacchus** [comment]
Fixed now, will be up next update. I also added config lines for max launch power that can be applied to entities.
