### ISSUE TITLE
[BUG] CHAOS ORB IS NOT WORKING

### ISSUE THREAD

**Issue by afradshad** [mariumbacchus/Soulslike-Weaponry#190]
Minecraft: 1.20.1
Fabric: 0.15.9
Soulslike-Weaponry: 1.1.3

Hi so i play on a server with my friends, we also use other mods. We were trying to throw the chaos orb so we can fight the day stalker and night crawler but its not throwing nor spawning them in please help THANKS

**Comment by afradshad** [comment]
![Screenshot 2024-09-17 020114](https://github.com/user-attachments/assets/4f40fd87-bcbc-46e5-9be8-734e6bf75506)
![Screenshot 2024-09-17 020128](https://github.com/user-attachments/assets/f32c298f-969a-45b4-903b-7c6144cbea73)
a picture of the mods

**Comment by mariumbacchus** [comment]
The fact that you can't even throw it tells me there is a conflict with other mods. If there are any mods that you know of which overwrite an item's use method (like how Spell Engine overwrites use methods of items to use it's own spells) then check if there are configs where you can blacklist/whitelist the use of the item. TLDR:
- Find the mod that causes the conflict
- See if the mod has a config where you can blacklist/whitelist the item so it can be used normally

**Comment by afradshad** [comment]
hmm alright ill try but what mod do you think it is? since im sure you got a lot of reports about it not working from other people

**Comment by mariumbacchus** [comment]
No I haven't, or at least not that I remember. I have only gotten it regarding the weapons, not the orb. Either way, if it works in isolation without other mods, then there has to be other mods causing the issue. Spell Engine did cause issues back in the day, other than that I'm not sure which one could cause it sadly.

**Comment by mariumbacchus** [comment]
I just noticed from your picture you have installed version 0.9.9.6, not the latest version (1.1.4), no wonder it's not working if you have an outdated version. Verify this please.

**Comment by afradshad** [comment]
yep so the issue was i had an outdated one and also i didnt have ranged_weapon api which is needed for this mod. Also another mod was outdated thanks for the help

**Comment by mariumbacchus** [comment]
No problem, glad it worked out
