### ISSUE TITLE
[BUG] Possible interaction issue with Bewitchment

### ISSUE THREAD

**Issue by Pingu-Pox** [mariumbacchus/Soulslike-Weaponry#191]
**Minecraft, modloader and mod versions**
The platform is a Fabric server running version "0.15.11".
The detected Minecraft version is "1.20.1".
The process is using Java 21.0.4 (Temurin-21.0.4+7 from Eclipse Adoptium)

Soulslike-Weaponry: soulslike-weaponry-1.1.4.2-1.20.1-fabric
Bewitchment: bewitchment-1.20-8

**Describe the bug**
A above-average portion of the tick loop is taken up by Marium's Soulslike Weaponry's Forlorn mobs being affected by Bewitchment's `canHaveStatusEffect()` method seen [here](https://github.com/MoriyaShiine/bewitchment/blob/3abbf30e6bfdfbd0053085fe84bd69daadca17b4/src/main/java/moriyashiine/bewitchment/mixin/sigil/LivingEntityMixin.java#L52)

**To Reproduce**
1. Host a server for v3.0.2 of Prominence II RPG: Hasturian Era
2. Connect to server with appropriate version of the modpack
3. Go to the nether
4. Watch performance tank on a server with a few people (TPS seems fine with 4 people based on the settings in my Spark profiler, but any more than that, TPS starts to tank to 10 or below)

**Expected behavior**
Unlike other mobs (Zombies, Skeletons, Creepers, etc.) the Forlorn seem to be affected strongly by Bewitchment's [canHaveStatusEffect()](https://github.com/MoriyaShiine/bewitchment/blob/3abbf30e6bfdfbd0053085fe84bd69daadca17b4/src/main/java/moriyashiine/bewitchment/mixin/sigil/LivingEntityMixin.java#L52). Being affected less or not at all would help with performance.

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/4ff86f0d-0599-4514-9db0-425a2e076f75)

**Other mods or relevant info**
Here's a [Spark profile ](https://spark.lucko.me/CGPCLVgtCC)of my server being affected by the issue. I have created a matching ticket for Bewitchment.

**Comment by Pingu-Pox** [comment]
https://github.com/MoriyaShiine/bewitchment/issues/409

**Comment by mariumbacchus** [comment]
Noted, will fix that.
