### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JawayWu** [mariumbacchus/Soulslike-Weaponry#195]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Forge: 47.3.10
Soulslike-Weaponry: 1.1.4.4d

**Describe the bug**
Crashes on Launch because dependency Projectile Damage Attribute is not the right version. Projectile Damage Attribute has a updated version 3.2.3, and soulslike requires 3.2.2. Can this be updated for the new version of Projectile Damage Attribute?

**Add logs**
-- MOD soulsweapons --
Details:
	Mod File: /D:/Minecraft Instances/Mystic Horizons/minecraft/mods/soulslike-weaponry-1.1.4.4d-1.20.1-forge.jar
	Failure message: Mod soulsweapons requires projectile_damage 3.2.2+1.20.1
		Currently, projectile_damage is 3.2.3+1.20.1
	Mod Version: 1.1.4.4d-1.20.1-forge}
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

**To Reproduce**
1. Launch the game with Soulslike Weaponry and Projectile Damage 3.2.3

**Expected behavior**
Minecraft is able to launch. 

**Screenshots and videos**
If relevant, add screenshots or videos to help explain your problem. For example: a video of you attempting to use a weapon that doesn't work.

**Other mods or relevant info**
Write down mods you are using you think could cause the issue due to conflicting code or incompatibility.

**Comment by mariumbacchus** [comment]
No, the last time I tested the newest version of projectile damage, it was unstable and crashed the game. As of now, I will force it to use 3.2.2 until I find this issue resolved.
