### ISSUE TITLE
Incompatibility with other mods

### ISSUE THREAD

**Issue by pufmat** [mariumbacchus/Soulslike-Weaponry#198]
Hi :wave: 

Players have found that some attributes from my [Pufferfish's Attributes mod](https://www.curseforge.com/minecraft/mc-mods/puffish-attributes) don't work with Soulslike Weaponry. I investigated it and found that the issue is caused by this mixin:
https://github.com/mariumbacchus/Soulslike-Weaponry/blob/51aa683df513597e062e53bb542fa90fc847fc6b/src/main/java/net/soulsweaponry/mixin/LivingEntityMixin.java#L32-L37
Here and in the other places your mod uses `@Inject` to modify return value. This way makes it incompatible with other mods that try to modify the same value. Consider using [`@ModifyReturnValue`](https://github.com/LlamaLad7/MixinExtras/wiki/ModifyReturnValue) instead of `@Inject` as it allows multiple mods to modify the same value.

**Comment by mariumbacchus** [comment]
Hi, thanks for reaching out about this! Didn't realize this would cause conflicts, will fix this for the next update.

**Comment by mariumbacchus** [comment]
Fixed in [this commit](https://github.com/mariumbacchus/Soulslike-Weaponry/commit/8b39d627c3d1bede4a413d91d1e5367bd436f2c3#diff-a841355877b77126011120c3bef9afbccefc7e24729642e704faef32cb6dde45), will be up next update.
