### ISSUE TITLE
bosses not working w/ old moon altar

### ISSUE THREAD

**Issue by maxmontes42** [mariumbacchus/Soulslike-Weaponry#2]
For some reason the old moon altar will only summon the Returning Knight boss and not the other two. The Monarch of Chaos worked fine, it’s just the Fallen Icon and Champion’s Remains that don’t seem to work for me. I’m playing on Fabric 1.19.2 with the Dark RPG modpack.

**Comment by mariumbacchus** [comment]
I believe the version on Dark RPG is outdated. That would be the only logical explanation.
