### ISSUE TITLE
[BUG] Config issue

### ISSUE THREAD

**Issue by KiraKayn** [mariumbacchus/Soulslike-Weaponry#200]
**Minecraft, modloader and mod versions**
Minecraft: 1.20.1
Forge: 47.3.7
Soulslike-Weaponry: 1.1.5

**Describe the bug**
I cant turn off the parrying system, I have the config on false, but the description still appears on shields

**Add logs**
[latest.log](https://github.com/user-attachments/files/17561451/latest.log)

**To Reproduce**
1. Locate the enable_shield_parry line in the config file
2. Set it to false
3. Launch the game and you'll see that the shields still got the description

**Expected behavior**
I expected it to delete the text from the shields ofcourse.

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/6e0ac7a1-e7ae-4126-8c95-d460a1630fb4)
![image](https://github.com/user-attachments/assets/2bb734b5-fb5b-43e0-bcd7-4985cb3250b0)

**Other mods or relevant info**
Dont think its a compat issue, but I've got a huge modlist so if you want me to send them I can send it in a file

**Comment by mariumbacchus** [comment]
That's just an oversight, will be fixed.

**Comment by mariumbacchus** [comment]
Fixed in [this commit](https://github.com/mariumbacchus/Soulslike-Weaponry/commit/8b39d627c3d1bede4a413d91d1e5367bd436f2c3#diff-8ea2162cfd845d60fa2c8f0ce170c068a3a774d3ea03a1fd0ff47112c41cc0ba)

**Comment by KiraKayn** [comment]
@mariumbacchus 
Hi! Idk if Im being dumb but is this fix not uploaded yet?

**Comment by mariumbacchus** [comment]
Haven't made a forge version of the new update yet since there is a LOT to port over, but it is fixed.
