### ISSUE TITLE
[BUG] Bluemoon Shortsword ability is bugged I think

### ISSUE THREAD

**Issue by KiraKayn** [mariumbacchus/Soulslike-Weaponry#201]
**Minecraft, modloader and mod versions**
Minecraft: 1.20.1
Forge: 43.3.0
Soulslike-Weaponry: 1.1.5

**Describe the bug**
The bluemoon shortsword shoots the projectiles continuously every 2 about ticks, while the upgraded version of it only shoots 1/swing animation

**Add logs**
[latest.log](https://github.com/user-attachments/files/17604337/latest.18.log)

**To Reproduce**

**Expected behavior**
There is supposed to be a cooldown between shots I believe, but for some reason theres not. It's probably a minor thing

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/5ea0489c-7298-42b2-8dee-966a0198ec71)

**Other mods or relevant info**

**Comment by mariumbacchus** [comment]
Yeah it's a known issue which only occurs in creative, hense why I haven't bothered fixing it. I'll patch it up next update.

**Comment by mariumbacchus** [comment]
Fixed for next update.
