### ISSUE TITLE
[FEATURE][Forge 1.1.5] Dependencies are not declared for this specific version on the CurseForge page

### ISSUE THREAD

**Issue by snekaholic** [mariumbacchus/Soulslike-Weaponry#203]
Upon installing the mod through the CurseForge launcher, it will not install the dependencies, causing crash on startup. Just a human error, it happens. Still figured I should point it out. Great mod <3

- Snek

**Comment by mariumbacchus** [comment]
Thanks for pointing it out, fixed now!
