### ISSUE TITLE
projectile damage missing?

### ISSUE THREAD

**Issue by capablecolt9** [mariumbacchus/Soulslike-Weaponry#206]
this is my first issue ive reported about any mod so im not sure what to put but it is just telling me to download projectile_damage, the only thing i can find though is for 1.20.2 and below and im on 1.20.4, i appreciate your time.

**Comment by mariumbacchus** [comment]
I get that it looks confusing since it doesn't outright display 1.20.4, but if you read the description of this version [here](https://modrinth.com/mod/projectile-damage-attribute/version/3.2.2+1.20.2-fabric), then it says it supports every version of 1.20.X.
Hope this helps!

**Comment by LEADRACER** [comment]
is that the attribute thing or something else
