### ISSUE TITLE
[BUG] Adding smite to Comet Spear causes Riptide ability to throw player much further

### ISSUE THREAD

**Issue by kurealnum** [mariumbacchus/Soulslike-Weaponry#210]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Fabric: 47.3.0
Soulslike-Weaponry: 1.1.5

**Describe the bug**
The Comet Spear's ability is amplified when Smite is applied 

**To Reproduce**
1. Enchant Comet Spear with Smite 4 - 5
2. Use the Comet Spears ability
3. Observe yourself flying 100 blocks into the air

**Expected behavior**
I think the Comet Spear's ability is supposed to be static (in other words, not dependent on any enchants)? If it's not, this isn't a bug. 

As a side note, the same effect seems to occur when using any level of smite (tried smite 4 and 5). 

**Screenshots and videos**
Video: https://www.youtube.com/watch?v=WaAMLQ4b46Y

**Other mods or relevant info**
None.

**Comment by mariumbacchus** [comment]
It's not static, this is intended. It will also happen with Sharpness and BOA.
