### ISSUE TITLE
[FEATURE] Change to documentation/wiki for Comet Spear 

### ISSUE THREAD

**Issue by kurealnum** [mariumbacchus/Soulslike-Weaponry#211]
**Is your feature request related to a problem? Please describe.**
No, just an addition to documentation. 

**Describe the solution you'd like**
I'm the guy who recently had a question about the Comet Spear's ability. I couldn't find anything in the wiki about the increase in strength of the Grand Skyfall ability based on the Sharpness/Smite level, so I'd like to add something to the Comet Spear's entry. Just something like "The Grand Skyfall ability will scale based on the level of Sharpness/Smite". 

I'd be happy to do this and make a PR myself, but I don't know if I can directly make PR's on a wiki. 

Thank you for your work by the way! I've been using this on my server for about a week now, and it's been wonderful.

**Comment by mariumbacchus** [comment]
Sure, I've updated the wiki now to state the bonus flight based on enchants (added it for Mjolnir aswell). Thank you for the kind words!

**Comment by kurealnum** [comment]
Awesome, thank you, and no problem!
