### ISSUE TITLE
[BUG] Conflict With Puffish Skills

### ISSUE THREAD

**Issue by EmoBubbleGum** [mariumbacchus/Soulslike-Weaponry#214]
Minecraft: 1.18.2
Forge: 40.2.21
Soulslike-Weaponry: 1.1.5

Breaks the resistance attribute of puffish skills if using both mods together. Causes the attribute to do nothing. 

My edited config with the first resistance node set to 90% for testing:
[puffish config.zip](https://github.com/user-attachments/files/18277158/puffish.config.zip)
Just extract into config folder.

**Comment by mariumbacchus** [comment]
Bugs with pufferfish skills mod has been fixed already for the next update. Changes will be live when the update is released.

**Comment by EmoBubbleGum** [comment]
oh sweet, me and my bro were really bummed about having to take your mod out of the pack. look forward to it.

**Comment by EmoBubbleGum** [comment]
Seems this update never came to 1.18.2? I'm working on a pack for it and really want to include it :(

**Comment by mariumbacchus** [comment]
I get your dissapointment, but working on 4+ versions across both fabric and forge is just too much and prevents me from adding new content, so no I don't plan on updating 1.18.2 in the near future.
