### ISSUE TITLE
[BUG] Can't launch game while exclusively using this mod?

### ISSUE THREAD

**Issue by EmoBubbleGum** [mariumbacchus/Soulslike-Weaponry#215]
Minecraft: 1.18.2
Forge: 40.2.31
Soulslike-Weaponry: 1.1.5

Crashes when trying to launch? Are there hidden dependencies? I was trying to launch it on vanilla to test and make sure the puffish conflict happens with with no other mods, but it crashes. Even crashes with the only mod being soulslike...

[crash-2024-12-30_14.11.07-client.txt](https://github.com/user-attachments/files/18277249/crash-2024-12-30_14.11.07-client.txt)

**Comment by mariumbacchus** [comment]
You're likely missing the correct version of geckolib, make sure you downloaded the latest version for forge. The only dependencies are Attributefix, Projectile damage attribute and geckolib.

**Comment by EmoBubbleGum** [comment]
I figured it was something like that, you should add them all to the dependencies section.
