### ISSUE TITLE
Here is my crash log that you've been asking for.

### ISSUE THREAD

**Issue by makumaku1974** [mariumbacchus/Soulslike-Weaponry#22]
[crashlog1.txt](https://github.com/mariumbacchus/Soulslike-Weaponry/files/11278409/crashlog1.txt)

**Comment by mariumbacchus** [comment]
Alright, so there is a lot wrong here. From what I can gather, some other mod is conflicting with SW. Some mods were even missing, and from personal experience, I think Optifine and Immersive Portals don't work together (unless they found a fix for that, I might be wrong). Anyway, I found one thing I think I can fix, but I am not sure this will fix everything. Alone, SW works fine, so you can try to launch without your other mods and see if that works, then you can slowly add the other mods back in and then find which mod is causing trouble. If you do that, then I might be able to fix the issue.

**Comment by mariumbacchus** [comment]
Looks like there is a mod titled "iceberg" that intervenes with the renderering of the item. See if removing this mod helps.

**Comment by mariumbacchus** [comment]
Closing this as I believe I've fixed the issue and since there has not been any feedback to my suggestions.
