### ISSUE TITLE
Undying King HP [Bug]

### ISSUE THREAD

**Issue by Haikiyu** [mariumbacchus/Soulslike-Weaponry#23]
The HP of the Undying King still starts at the base HP no matter what's in the config.

This is for the latest version of the mod for 1.19.2.

**Comment by mariumbacchus** [comment]
Keep in mind that the notches on his health bar does NOT represent a mark on his health (such as 100 hp for each notch), it is simply there for aesthetics (for now).

**Comment by mariumbacchus** [comment]
Closing due to lack of response.
