### ISSUE TITLE
Galeforce always boosts.

### ISSUE THREAD

**Issue by notIkibo** [mariumbacchus/Soulslike-Weaponry#24]
Description says after max pull, but u can spam right click and have infinite Speed boost.
In Off Hand you also get a dash (with cd), but also even after one right click.

Kinda op ngl

And I love calculated fall for darkin blade, but movement is so weird. you just get a little boost upwards with almost no momentum. I guess I kinda expected it to slingshot (to a degree) you wherever you look..
Don't know what's your planning with that.
Ik Aatrox is not that mobile with his Q, but also combine Q with his E. :3
So yeah, not that fun to use it for only jump basically.

**Comment by notIkibo** [comment]
Oh and what is Umbral Trespass and how can I use it? Against whom? Really no clue

**Comment by mariumbacchus** [comment]
Umbral Trespass "mounts" the last mob you hit when using it. In this state, you take no damage, and on dismount, you will damage the mob.
I do know of the Galeforce bug, haven't decided whether I want it to be a feature or not, but yeah I agree that it is kinda op.
As for the Darkin Blade, I'll add a small boost so it feels less clunky.
