### ISSUE TITLE
Entity default attacks

### ISSUE THREAD

**Issue by itsdinkd** [mariumbacchus/Soulslike-Weaponry#27]
Can you please list out the _**default**_ attack damage of each boss? This way we know what the modifier in the config is actually modifying

**Example**
if I use 2.0 for `fallen_icon_damage_modifier` what is it multiplying by 2?

**Comment by mariumbacchus** [comment]
It modifies every single attack. The damage of each attack differs. 2.0 will double the damage of all it's attacks, while 0.5 will half it.

**Comment by itsdinkd** [comment]
> It modifies every single attack. The damage of each attack differs. 2.0 will double the damage of all it's attacks, while 0.5 will half it.

Yes I understand how multiplication works. I am asking if you can write out each entities original attack damage so I know what I am multiplying to. Does the fallen icon do 5 damage? Or 20? 

What is the original damage for each boss

**Comment by mariumbacchus** [comment]
Fallen Icon:
- Blinding Light: 20, 15 for projectiles in phase 2
- Eruption: 35
- Mace Of Spades: 20 first hit, 25 second hit
- Obliterate: 50
- Moonveil: 50
- Moonfall: 30 for each erruption, 65 on the place the sword hits
- Thrust: 50
- Sword of Light: 25 for both projectiles and sword swipe
- Core Beam: 20

If you're interested in seeing the damage for the other bosses, then I suggest going into the ai/goal files yourself and look for when the damage modifier methods are used.

**Comment by itsdinkd** [comment]
Sure, can you send me the locations of the files?

**Comment by mariumbacchus** [comment]
I will put them all up on the wiki when I can.
