### ISSUE TITLE
Crash on 1.19.4

### ISSUE THREAD

**Issue by NantaArthur123** [mariumbacchus/Soulslike-Weaponry#30]
I don't know what happened, sorry cannot help much, the thing is I just hop into server and after 3 minutes my mc crashed.

crash log:
[crash-2023-05-15_17.05.32-client.txt](https://github.com/mariumbacchus/Soulslike-Weaponry/files/11476659/crash-2023-05-15_17.05.32-client.txt)

**Comment by mariumbacchus** [comment]
It is caused by a conflict between the Iceberg mod and SW. Will be fixed.
