### ISSUE TITLE
No config file? Structures not compatible with terralith. 

### ISSUE THREAD

**Issue by bellakeys** [mariumbacchus/Soulslike-Weaponry#31]
I love this mod, but with terralith installed the structures spawn in very strange places. Its immersion breaking for me, it would be nice to either have mod compat or a config! 

Thanks!

**Comment by Shibva** [comment]
there is a config file; though its not picked up by the mods that read configs. there is HOWEVER a config file you can edit

IMPORTANT NOTE: avoid using notepad to edit json files; it messes them up and wont save properly; use a different thing like VSC or another json compatible option

AS for terralith, thats a datapack gen thing; would be intresting nontheless to have compat wtih it


as for the config, it might be possible to have it work with the config mods, but may take a bit of tinekring; tbh im not sure the process

**Comment by Apollounknowndev** [comment]
What is Terralith supposed to do about compatibility when you don't use the biome tags that exist specifically for compatibility with Terralith/other worldgen mods?
