### ISSUE TITLE
Ticking entity error

### ISSUE THREAD

**Issue by onycius** [mariumbacchus/Soulslike-Weaponry#32]
Hello! I'm experimenting with adjusting the stats of the bosses on Fabric 1.19.2, and I encountering ticking entity problems that may or may not be related to Soulslike Weaponry. I have confirmed that this is not due to the Neruina mod present (which deals with kicking/killing invalid ticking of entities).

Is there a health or damage cap that prevents the bosses from working properly? Here is the full log and config:

https://mclo.gs/5KAGvAB

{
  "disable_all_legendary_recipes": false,
  "disable_gun_recipes": false,
  "disable_all_enchantments": false,
  "disable_enchantment_fast_hands": false,
  "disable_enchantment_posture_breaker": false,
  "disable_enchantment_stagger": false,
  "disable_recipe_bloodthirster": false,
  "disable_recipe_comet_spear": false,
  "disable_recipe_darkin_blade": false,
  "disable_recipe_dawnbreaker": false,
  "disable_recipe_heap_of_raw_iron": false,
  "disable_recipe_dragonslayer_swordspear": false,
  "disable_recipe_dragon_staff": false,
  "disable_recipe_draugr": false,
  "disable_recipe_galeforce": false,
  "disable_recipe_rageblade": false,
  "disable_recipe_lich_bane": false,
  "disable_recipe_moonlight_greatsword": false,
  "disable_recipe_moonlight_shortsword": false,
  "disable_recipe_nightfall": false,
  "disable_recipe_soul_reaper": false,
  "disable_recipe_whirligig_sawblade": false,
  "disable_recipe_withered_wabbajack": false,
  "disable_recipe_leviathan_axe": false,
  "disable_recipe_skofnung": false,
  "disable_recipe_pure_moonlight_greatsword": false,
  "disable_recipe_mjolnir": false,
  "disable_recipe_sword_of_freyr": false,
  "disable_recipe_sting": false,
  "disable_recipe_featherlight": false,
  "disable_recipe_crucible_sword": false,
  "disable_recipe_darkin_scythe": false,
  "disable_recipe_kirkhammer": false,
  "disable_recipe_ludwigs_holy_blade": false,
  "disable_recipe_draupnir_spear": false,
  "disable_recipe_holy_moonlight_sword": false,
  "withered_demon_spawnrate": 20,
  "moderatly_sized_chungus_spawnrate": 20,
  "evil_forlorn_spawnrate": 10,
  "can_withered_demon_spawn": true,
  "can_moderatly_sized_chungus_spawn": true,
  "can_evil_forlorn_spawn": true,
  "bloodthirster_damage": 8,
  "bloodthirster_overshields": true,
  "lifesteal_item_base_healing": 2,
  "lifesteal_item_heal_scales": true,
  "lifesteal_item_cooldown": 60,
  "bluemoon_greatsword_damage": 8,
  "bluemoon_shortsword_damage": 7,
  "comet_spear_damage": 9,
  "comet_spear_projectile_damage": 9.0,
  "comet_spear_ability_damage": 10.0,
  "comet_spear_skyfall_ability_cooldown": 400,
  "comet_spear_throw_ability_cooldown": 25,
  "crucible_sword_normal_damage": 9,
  "crucible_sword_empowered_damage": 30,
  "crucible_sword_empowered_cooldown": 300,
  "darkin_blade_damage": 13,
  "darkin_blade_ability_damage": 14.0,
  "darkin_blade_ability_cooldown": 150,
  "darkin_scythe_damage": 11,
  "darkin_scythe_bonus_damage": 3,
  "darkin_scythe_max_souls": 100,
  "darkin_scythe_prime_ability_damage": 20.0,
  "darkin_scythe_prime_ability_percent_health_damage": 10.0,
  "darkin_scythe_prime_ability_cooldown": 400,
  "darkin_scythe_prime_heal_modifier": 0.25,
  "darkin_scythe_prime_ticks_before_dismount": 80,
  "dawnbreaker_damage": 8,
  "dawnbreaker_ability_damage": 10.0,
  "dawnbreaker_ability_chance_modifier": 0.0,
  "dawnbreaker_affect_all_entities": false,
  "heap_of_raw_iron_damage": 10,
  "heap_of_raw_iron_cooldown": 200,
  "dragonslayer_swordspear_damage": 11,
  "dragonslayer_swordspear_projectile_damage": 9.0,
  "dragonslayer_swordspear_ability_damage": 6.0,
  "dragonslayer_swordspear_lightning_amount": 1,
  "dragonslayer_swordspear_throw_cooldown": 100,
  "dragonslayer_swordspear_ability_cooldown": 300,
  "dragon_staff_damage": 10,
  "dragon_staff_aura_strength": 1,
  "dragon_staff_cooldown": 100,
  "dragon_staff_use_time": 100,
  "draugr_damage_at_night": 10,
  "draupnir_spear_damage": 10,
  "draupnir_spear_projectile_damage": 10.0,
  "draupnir_spear_detonate_power": 1.0,
  "draupnir_spear_throw_cooldown": 40,
  "draupnir_spear_detonate_cooldown": 100,
  "draupnir_spear_max_age": 400,
  "forlorn_scythe_damage": 11,
  "featherlight_damage": 10,
  "featherlight_attack_speed": 1.6,
  "galeforce_bonus_damage": 1.0,
  "galeforce_dash_cooldown": 50,
  "rageblade_damage": 10,
  "rageblade_haste_cap": true,
  "holy_moonlight_greatsword_damage": 12,
  "holy_moonlight_ability_charge_needed": 50,
  "holy_moonlight_ability_charge_added_post_hit": 1,
  "holy_moonlight_ability_damage": 20.0,
  "holy_moonlight_ability_knockup": 0.3,
  "holy_moonlight_ability_cooldown": 150,
  "holy_moonlight_sword_damage": 8,
  "kirkhammer_damage": 9,
  "kirkhammer_silver_sword_damage": 6,
  "leviathan_axe_damage": 11,
  "leviathan_axe_projectile_damage": 8.0,
  "leviathan_axe_return_speed": 4.0,
  "lich_bane_damage": 10,
  "lich_bane_bonus_magic_damage": 2.0,
  "ludwigs_holy_greatsword": 8,
  "righteous_undead_bonus_damage": 2.0,
  "mjolnir_damage": 16,
  "mjolnir_rain_bonus_damage": 4,
  "mjolnir_smash_damage": 12.0,
  "mjolnir_projectile_damage": 10.0,
  "mjolnir_lightning_smash_cooldown": 200,
  "mjolnir_riptide_cooldown": 300,
  "mjolnir_return_speed": 4.0,
  "moonlight_greatsword_damage": 12,
  "moonlight_greatsword_projectile_damage": 8.0,
  "pure_moonlight_greatsword_damage": 14,
  "moonlight_shortsword_damage": 10,
  "moonlight_shortsword_projectile_damage": 3.0,
  "moonlight_shortsword_projectile_cooldown": 13,
  "moonlight_shortsword_enable_right_click": false,
  "moonlight_shortsword_enable_left_click": true,
  "nightfall_damage": 11,
  "nightfall_ability_damage": 18.0,
  "nightfall_ability_shield_power": 2,
  "nightfall_shield_cooldown": 500,
  "nightfall_smash_cooldown": 300,
  "nightfall_summon_chance": 0.3,
  "shadow_assassin_scythe_shadow_step_bonus_damage": 2,
  "shadow_assassin_scythe_shadow_step_ticks": 60,
  "shadow_assassin_scythe_shadow_step_cooldown": 100,
  "shadow_assassin_scythe_ability_damage": 40.0,
  "shadow_assassin_scythe_ability_cooldown": 300,
  "shadow_assassin_scythe_ticks_before_dismount": 120,
  "skofnung_damage": 8,
  "skofnung_bonus_damage": 2,
  "skofnung_disable_heal_duration": 100,
  "skofnung_stone_additional_empowered_strikes": 8,
  "soulreaper_damage": 11,
  "sting_damage": 6,
  "sting_bonus_arthropod_damage": 4.0,
  "sword_of_freyr_damage": 14,
  "whirligig_sawblade_damage": 8,
  "whirligig_sawblade_ability_damage": 5.0,
  "whirligig_sawblade_cooldown": 100,
  "whirligig_sawblade_use_time": 100,
  "withered_wabbajack_damage": 8,
  "can_projectiles_apply_posture_break": true,
  "blunderbuss_damage": 9,
  "blunderbuss_cooldown": 40,
  "gatling_gun_damage": 2,
  "gatling_gun_startup_time": 40,
  "hunter_cannon_damage": 13,
  "hunter_cannon_cooldown": 180,
  "hunter_pistol_damage": 3,
  "hunter_pistol_cooldown": 20,
    //
  "decaying_king_health": 11000.0,
  "decaying_king_attack_cooldown_ticks": 10,
  "decaying_king_special_cooldown_ticks": 40,
  "decaying_king_damage_modifier": 2.55,
    //
  "returning_knight_health": 16000.0,
  "returning_knight_attack_cooldown_ticks": 20,
  "returning_knight_special_cooldown_ticks": 60,
  "returning_knight_damage_modifier": 2.75,
    //
  "old_champions_remains_health": 4000.0,
  "old_champions_remains_attack_cooldown_ticks": 10,
  "old_champions_remains_special_cooldown_ticks": 160,
  "old_champions_remains_damage_modifier": 2.55,
  "old_champions_remains_hits_before_growing_resistant": 6,
    //
  "frenzied_shade_health": 800.0,
  "frenzied_shade_damage_modifier": 2.75,
  "frenzied_shade_cooldown": 10,
    //
  "chaos_monarch_health": 8000.0,
  "chaos_monarch_attack_cooldown_ticks": 30,
  "chaos_monarch_damage_modifier": 2.75,
    //
  "fallen_icon_health": 24000.0,
  "fallen_icon_attack_cooldown_ticks_phase_1": 20,
  "fallen_icon_attack_cooldown_ticks_phase_2": 0,
  "fallen_icon_special_cooldown_ticks": 20,
  "fallen_icon_damage_modifier": 3.05
}

**Comment by mariumbacchus** [comment]
Minecraft has capped all health to 1024 health, but that alone would not crash the game. I don't think SW has anything to do with the crash, I see a lot of error messages such as configs not loading properly or mods not applying properly (especially mixins), but none that has SW's tag/id to it. I am working on a fix that increases the max health threshold minecraft has hardcoded.
