### ISSUE TITLE
Texture Issue causes mipmap level to be forced to zero

### ISSUE THREAD

**Issue by Poke097** [mariumbacchus/Soulslike-Weaponry#33]
01:07:23.955
net.minecraft.class_1059
Worker-ResourceReload-5
Texture soulsweapons:item/dragon_staff_textures_old with size 29x29 limits mip level from 1 to 0

This ^ causes the mipmap level to be forced to 0 and makes the game crispy and it also breaks the entire atlas

**Comment by pokesmells** [comment]
Has this been fixed on 1.19.2 or above? I've seen updates on this mod but the mipmap issue still persists on the version available on 1.19.2

**Comment by mariumbacchus** [comment]
It has been fixed, but no update for 1.19.2 has been published yet with that fix in.

**Comment by pokesmells** [comment]
> It has been fixed, but no update for 1.19.2 has been published yet with that fix in.

When do you reckon it'll be released?

**Comment by mariumbacchus** [comment]
The plan is to release it as the full 1.0.0 update since I've slowly added new, but unfinished content to the 1.19.2 version, so it may take a while.
