### ISSUE TITLE
Bug with Soul Reaper weapon [0.9.9.2]

### ISSUE THREAD

**Issue by HallisCode** [mariumbacchus/Soulslike-Weaponry#34]
Version : soulslike-weaponry-0.9.9.2

Soul Reaper weapon

If you accumulate 30 souls and summon a Familiar, Soulmass will come who summons his Familiars. If you recall the souls back, we get 30 souls + souls of his companions back to the weapon. I was literally able to fill a scythe for 1000 souls in 5 minutes. Fix please.

Also, this familiar for 30 souls infinitely ghosts spawn, limit that he could not call more creatures if they are let's say 5. Otherwise it's too imbalanced weapon. I literally for 30 souls summon a bexonetic army.

**Comment by mariumbacchus** [comment]
Sounds awesome and funny as hell, will be fixed.
