### ISSUE TITLE
[SUGGESTION] Disable bosses breaking blocks

### ISSUE THREAD

**Issue by KevzCz** [mariumbacchus/Soulslike-Weaponry#40]
Can we have this as an option in the config? We use FLAN as a claiming mod and i saw that they don't protect blocks from being broken and the boss can be used to grief. Thanks a lot if you're able to!

**Comment by mariumbacchus** [comment]
I am guessing you're referring to the Returning Knight and Fallen Icon. The doMobGriefing gamerule still applies to them, but I'll add another way of disabling it in the config soon.
