### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by Mahadbaloch** [mariumbacchus/Soulslike-Weaponry#43]
Any estimate of how long?

**Comment by mariumbacchus** [comment]
I am considering adding all the new 1.0.0 content currently made with the 1.20 version. In that case, it would be like a beta version of the mod update. If I notice that it takes too much time, then I'll make the 1.20 port sooner.

**Comment by Mahadbaloch** [comment]
I see there is a 1.20.1 version now. Does that mean no 1.20? :(

**Comment by mariumbacchus** [comment]
Is it necessary for your other mods? I believe most others are compatible with 1.20.1.

**Comment by mariumbacchus** [comment]
I'll see what I can do to make it compatible with 1.20.

**Comment by mariumbacchus** [comment]
Newest version coming in a few minutes now works for both 1.20 and 1.20.1.

**Comment by Mahadbaloch** [comment]
Thanks you are awesome. Always love to play with this mod
