### ISSUE TITLE
Drown Model Bug, possible imcompatibility? Fabric 1.20

### ISSUE THREAD

**Issue by rainysux** [mariumbacchus/Soulslike-Weaponry#47]
![2023-07-07_14 22 24](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/113203852/d98e7367-2512-4756-8bbf-73707d636016)
![2023-07-07_14 22 32](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/113203852/8fb439cc-e85c-4a0e-80e8-8bd7b85f9c79)
I noticed the drowns in my games are weirdly off and they look like this when this mod is downloaded. Could be a possible incompatibilty with a mod.

**Comment by rainysux** [comment]
Maybe Fresh Animations since it makes animations for mobs.

**Comment by mariumbacchus** [comment]
You're right, this has nothing to do with Soulslike Weaponry. This mod doesn't affect drowned in any way.

**Comment by rainysux** [comment]
everytime i turn off souls like weapons, the drowns reverts back to normal
