### ISSUE TITLE
[1.19.2] InterceptOnHit crash

### ISSUE THREAD

**Issue by itsdinkd** [mariumbacchus/Soulslike-Weaponry#5]
wanted to bring awareness of this crash a player has received that corrupted their chunk in a older version of my modpack, AQM2. 

https://github.com/itsdinkd/AQM2/issues/158 

not sure if this was fixed or not with later versions of soulslike

**Comment by mariumbacchus** [comment]
Has been fixed, was caused by firing an arrow without an owner, for example through a dispenser.
