### ISSUE TITLE
Unintended Behavior involving guns

### ISSUE THREAD

**Issue by asantistevan** [mariumbacchus/Soulslike-Weaponry#51]
I am playing the modpack DarkRPG using fabric and Minecraft 1.20. We haven't modified the pack besides adding Essentials, removing Better Combat, and adding additional origin types.

I have found that the Hunter Cannon, Blunderbuss, Gatling Gun, and Pistol projectiles fall upwards when firing, instead of the expected behavior of falling downwards. 

I haven't found any information online, so before I build the project myself I figured I would check and see if there was a quick fix available. 
Thanks,

**Comment by mariumbacchus** [comment]
It is a known issue and only a rendering error. Shouldn't impact gameplay.
