### ISSUE TITLE
Frenzied shade goes underground mid fight, never to return.

### ISSUE THREAD

**Issue by Mahadbaloch** [mariumbacchus/Soulslike-Weaponry#53]
It has happened thrice now. It goes underground when fighting, but rather than resurfacing it just stays under. Sometimes wandering hundreds of blocks away
You can now see the bossbar when in the area
but not the boss or hear it, and another such area nearby where another one wandered away.

**Comment by mariumbacchus** [comment]
Fixed in upcoming update.
