### ISSUE TITLE
Log spamming error text with soulsweapons mentioned, no effect in game though(i think)

### ISSUE THREAD

**Issue by Mahadbaloch** [mariumbacchus/Soulslike-Weaponry#58]
Heres the thing it spams alot, it sometimes varies with a couple numbers, but its basically identical everytime and i dont know what the cause or pattern.

[15:37:11] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2828$class_2829@23cad748, suppressing error
--
14796 | org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_5643 is not cancellable.
14797 | at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
14798 | at net.minecraft.class_1309.handler$bmf000$soulsweapons$interceptDamage(class_1309.java:12190) ~[server-intermediary.jar:?]
14799 | at net.minecraft.class_1309.method_5643(class_1309.java) ~[server-intermediary.jar:?]
14800 | at net.minecraft.class_1657.method_5643(class_1657.java:928) ~[server-intermediary.jar:?]
14801 | at net.minecraft.class_3222.method_5643(class_3222.java:732) ~[server-intermediary.jar:?]
14802 | at net.minecraft.class_1309.method_5747(class_1309.java:1579) ~[server-intermediary.jar:?]
14803 | at net.minecraft.class_1657.method_5747(class_1657.java:1722) ~[server-intermediary.jar:?]
14804 | at net.minecraft.class_2248.method_9554(class_2248.java:457) ~[server-intermediary.jar:?]
14805 | at net.minecraft.class_1297.method_5623(class_1297.java:1287) ~[server-intermediary.jar:?]
14806 | at net.minecraft.class_1309.method_5623(class_1309.java:339) ~[server-intermediary.jar:?]
14807 | at net.minecraft.class_3222.method_14207(class_3222.java:1004) ~[server-intermediary.jar:?]
14808 | at net.minecraft.class_3244.method_12063(class_3244.java:1000) ~[server-intermediary.jar:?]
14809 | at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[server-intermediary.jar:?]
14810 | at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42) ~[server-intermediary.jar:?]
14811 | at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
14812 | at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
14813 | at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
14814 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
14815 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
14816 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
14817 | at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
14818 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
14819 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
14820 | at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
14821 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
14822 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
14823 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
14824 | at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by mariumbacchus** [comment]
Hopefully managed to fix it. Will be live next update.
