### ISSUE TITLE
Soulmass bugged.

### ISSUE THREAD

**Issue by Mahadbaloch** [mariumbacchus/Soulslike-Weaponry#59]
When spawned its like the dont exist initially. You cant touch them, they dont move, invunerable to tnt or arrows or melee, everything passes through, cannot collect them back. They stay this way until they move, which can be difficult. They can stay in place and attack mobs, staying glitched, but sometimes they chase and become normal. Other way is when owner go far away, then they teleport and become normal.

**Comment by mariumbacchus** [comment]
Could be an issue with your server connection if you were on one. Haven't had any similar issues, if it persists then make another bug report and I'll check it out.
