### ISSUE TITLE
Moonstone Compass cannot work in multiplayer games.

### ISSUE THREAD

**Issue by SmallYii** [mariumbacchus/Soulslike-Weaponry#6]
In multiplayer games, it will rotate irregularly, and it is impossible to locate the boss position.

**Comment by mariumbacchus** [comment]
Which version are you playing on? It takes time to find a location if it is far away. If there is no structure to be found, it will spin irregularly.

**Comment by SmallYii** [comment]
> Which version are you playing on? It takes time to find a location if it is far away. If there is no structure to be found, it will spin irregularly.

1.18.2 can't be used in the server, no matter how close to the boss will be irregular rotation.

**Comment by mariumbacchus** [comment]
Was thinking about the mod version as well, but I'll look into it.

**Comment by SmallYii** [comment]
> Was thinking about the mod version as well, but I'll look into it.

mod version 0.9.8 Thank you

**Comment by ereese99** [comment]
I am also experiencing this in 1.19.2, version 0.9.8
[crash-2023-03-14_02.43.46-server.txt](https://github.com/mariumbacchus/Soulslike-Weaponry/files/10980172/crash-2023-03-14_02.43.46-server.txt)
