### ISSUE TITLE
[1.20.1] Bosses do not spawn at full HP.

### ISSUE THREAD

**Issue by Sazuzaki** [mariumbacchus/Soulslike-Weaponry#60]
Heyo, I adjusted some max HP values in the config, and while they do apply, the bosses don't spawn with the maximum HP I specified.

![bug](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/20433987/29015a29-a170-4d58-8339-6c1ba9951f0a)

**Comment by mariumbacchus** [comment]
Fixed for the upcoming release.
