### ISSUE TITLE
Item: Big Chungus Music Disk *BUG*

### ISSUE THREAD

**Issue by Artisticraft** [mariumbacchus/Soulslike-Weaponry#61]
I am currently playing on AllOfFabric7 modpack and the disk was crafted and in my inventory. When I attempted to use it with the music box, the disk blinked out of existence. I checked my log on BISECT Hosting and there was no log for this issue. 

Marium's Soulslike Weaponry
Version 0.9.9.6 -1.20- fabric

**Comment by mariumbacchus** [comment]
Fixed for the upcoming update.
