### ISSUE TITLE
The controls menu is broken 

### ISSUE THREAD

**Issue by EvilWarriorZ** [mariumbacchus/Soulslike-Weaponry#62]
For some reason the mod do that the controls menu seems strange in fabric 1.20.1

**Comment by mariumbacchus** [comment]
Can you elaborate? Maybe provide picture?

**Comment by EvilWarriorZ** [comment]
Yeah for sure! I just realised that it just happen when you have the x4 or x3 GUI scale that it seems strange, when i put x2 or x1 it is ok. (The screenshots are not cut, it just seems like that in.game)
<img width="958" alt="Captura de pantalla 2023-09-12 225253" src="https://github.com/mariumbacchus/Soulslike-Weaponry/assets/127499569/122f3afd-d5a4-4728-b9bd-27df3b3c22f3">
<img width="960" alt="Captura de pantalla 2023-09-12 225339" src="https://github.com/mariumbacchus/Soulslike-Weaponry/assets/127499569/c471f159-6794-4923-8581-3e72a52c74fb">
Sorry if i make some mistakes, my english isn´t perfect but I hope you understand what I mean.

**Comment by mariumbacchus** [comment]
I am guessing it is because there's too much text so it overflows. Will be fixed.
