### ISSUE TITLE
some weapon abilities not working?

### ISSUE THREAD

**Issue by dxcently** [mariumbacchus/Soulslike-Weaponry#64]
After I updated the mod, the weapon abilites has stopped working, it might be because of conflicts from other mods, but rn I do not know what is causing it. I noticed that it was mainly the weapons with active(?) abilities (ones that you right click for). However the leviathan axe worked fine. 
video of this issue: https://streamable.com/7t4o46

**Comment by mariumbacchus** [comment]
If you're using Wizards (RPG Series), then you have to blacklist Soulslike Weaponry in Wizards (RPG Series)'s config, or at least the weapons not working.

**Comment by dxcently** [comment]
> You have to blacklist weapons from this mod in Wizards (RPG Series)'s config, namely Spell Enginge's. I'll see what I can do about implementing a permanent fix. To do it, go to the config folder, then into "spell_engine" and open the "server" file in notepad or vscode or any editing software. Look after "blacklist_spell_casting_regex" and type in "soulsweapons" in the empty " " space. That should do the trick.

this fixed it! thanks
