### ISSUE TITLE
Wizards (RPG Series) cause weapon not able to use right click abilities

### ISSUE THREAD

**Issue by AzulConspirator** [mariumbacchus/Soulslike-Weaponry#65]
Soul's Like version : 0.9.9.6 patch 2
Wizards version :  0.9.23
MC Ver : 1.20.1

using this mod in conjunction with Wizards (https://modrinth.com/mod/wizards) somehow disables any weapon from this mod to use its ability like the moonlight beams or the Whirligig Saw

no relevant log is outputted

**Comment by mariumbacchus** [comment]
You have to blacklist weapons from this mod in Wizards (RPG Series)'s config.
