### ISSUE TITLE
[SUGGESTION] Give bows more love!! + suggetions

### ISSUE THREAD

**Issue by dxcently** [mariumbacchus/Soulslike-Weaponry#66]
This mod has been a rlly fun experience so far, with all of the unique weapons and abilities, everything is just rlly fun to play with. 
However I would like to suggest to add more bows and refine galeforce! The issue I have with galeforce is that for the active rn - cloudburst you need to actually shoot an arrow, in league, it's an active ability so I think the mod should also reflect it, making it so that pressing the ability keybind will dash you forward and shoot execute-like arrows, scaling with how low the enemy is. 
The problem with this is that I can imagine it being a pain to implement a homing arrows feature, and also making it somehow scale with health%; the solution I've thought of is for the homing arrows, you can just not make it homing and shoot what is in front, and combined with a mod like [projectile damage attribute](https://legacy.curseforge.com/minecraft/mc-mods/projectile-damage-attribute) to scale the arrow damage, and it oc would only work through that mod other wise it would only deal 3 arrows worth of damage.
Some ranged weapons I think it'd be fun to see is something like caitlyn's sniper rifle, with guns already in the mod, adding a sniper rifle would fit in, and the ability can be like her in-game ult, with the aforementioned health% excute scaling.
Ashe's bow would also be really cool to see, shooting it would just apply a slow; the ability can make it so that each shot would also shoot 4-5 aditional arrows each shot.
Kraken slayer would also be a cool additional, it could have a relatively quick draw time, and every third shot would do "true damage" ignoring armor.
The Darkmoon Bow can also be implemented, shooting a modified smaller version of what the moonlight greatsword/master sword shoots, and it wouldn't use arrows, but a way to balance this would maybe making the durability lower.

some other random things I think it'd be cool to see would be like some sort of hook? like thresh's hook making it like a grappling hook kind of, or akshan's absolver.
Pyke's hook also could also be really cool, executing at like 10-15% health; right clicking would to throw the hook out, bringing mobs closer (and maybe "phase" through them and stunning), or pressing the ability key to "ult"; balancing could be making it so that the weapon only deals deal only 5-6 damage. (maybe adding a boss that spawns in the ocean as a way to get it?)
Youmuu's ghostblade

sorry bit of a long post, but this mod has been rlly fun, and i kinda just wanted to spill my ideas out. :)

**Comment by mariumbacchus** [comment]
Fantastic post! Love the different ideas you're coming with, I'll definitely consider adding some of them in the next big update ;)
As for the Galeforce, I agree that it needs some love. I'll see what I can do to bring it up a notch. Very cool suggestion!

**Comment by mariumbacchus** [comment]
Since Projectile Damage Attribute has been added and some bows too, I'm gonna close this. I've taken notes of the Pyke hook as a possible weapon for the future.
