### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by ItemAsylum** [mariumbacchus/Soulslike-Weaponry#67]
when summon the frost giant familiar using frostmourne (may include other weapons since i only tested it on one weapon), the game will crash about 4/10 times. Can anyone tell me if this is an issue with my laptop or the mod?

**Comment by mariumbacchus** [comment]
Can you give me the crash log?

**Comment by ItemAsylum** [comment]
uh for some reason its working again. Are there mods that are incompatible
with soulslike weaponry?

**Comment by mariumbacchus** [comment]
Don't know if there are any. If you give the crash log, I may be able to see what caused the crash.

**Comment by ItemAsylum** [comment]
ok here you go, btw sry for not replying for like a week
here is the report
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-10-24 23:38:35
Description: Ticking entity

java.lang.NoSuchMethodError: 'double
net.soulsweaponry.entity.mobs.FrostGiant$FrostGiantGoal.method_6289(net.minecraft.class_1309)'
at
net.soulsweaponry.entity.mobs.FrostGiant$FrostGiantGoal.method_6268(FrostGiant.java:239)
at net.minecraft.class_4135.method_6268(class_4135.java:65)
at net.minecraft.class_1355.method_38849(class_1355.java:120)
at net.minecraft.class_1355.method_6275(class_1355.java:111)
at net.minecraft.class_1308.method_6023(class_1308.java:774)
at net.minecraft.class_1309.method_6007(class_1309.java:2695)
at net.minecraft.class_1308.method_6007(class_1308.java:555)
at net.minecraft.class_1296.method_6007(class_1296.java:128)
at net.minecraft.class_1429.method_6007(class_1429.java:58)
at net.soulsweaponry.entity.mobs.Remnant.method_6007(Remnant.java:113)
at net.minecraft.class_1309.method_5773(class_1309.java:2449)
at net.minecraft.class_1308.method_5773(class_1308.java:356)
at net.soulsweaponry.entity.mobs.FrostGiant.method_5773(FrostGiant.java:182)
at net.minecraft.class_3218.method_18762(class_3218.java:745)
at net.minecraft.class_1937.method_18472(class_1937.java:480)
at net.minecraft.class_3218.method_31420(class_3218.java:385)
at net.minecraft.class_5574.method_31791(class_5574.java:54)
at net.minecraft.class_3218.method_18765(class_3218.java:353)
at
net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
at
net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:820)
at net.minecraft.class_1132.method_3748(class_1132.java:105)
at
net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
at
net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
at
net.soulsweaponry.entity.mobs.FrostGiant$FrostGiantGoal.method_6268(FrostGiant.java:239)
at net.minecraft.class_4135.method_6268(class_4135.java:65)
at net.minecraft.class_1355.method_38849(class_1355.java:120)
at net.minecraft.class_1355.method_6275(class_1355.java:111)
at net.minecraft.class_1308.method_6023(class_1308.java:774)
at net.minecraft.class_1309.method_6007(class_1309.java:2695)
at net.minecraft.class_1308.method_6007(class_1308.java:555)
at net.minecraft.class_1296.method_6007(class_1296.java:128)
at net.minecraft.class_1429.method_6007(class_1429.java:58)
at net.soulsweaponry.entity.mobs.Remnant.method_6007(Remnant.java:113)
at net.minecraft.class_1309.method_5773(class_1309.java:2449)
at net.minecraft.class_1308.method_5773(class_1308.java:356)
at net.soulsweaponry.entity.mobs.FrostGiant.method_5773(FrostGiant.java:182)
at net.minecraft.class_3218.method_18762(class_3218.java:745)
at net.minecraft.class_1937.method_18472(class_1937.java:480)
at net.minecraft.class_3218.method_31420(class_3218.java:385)
at net.minecraft.class_5574.method_31791(class_5574.java:54)
at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
Entity Type: soulsweapons:frost_giant
(net.soulsweaponry.entity.mobs.FrostGiant)
Entity ID: 9592
Entity Name: Frost Giant
Entity's Exact location: 739.17, 69.00, 907.17
Entity's Block location: World: (739,69,907), Section: (at 3,5,11 in
46,4,56; chunk contains blocks 736,-64,896 to 751,319,911), Region: (1,1;
contains chunks 32,32 to 63,63, blocks 512,-64,512 to 1023,319,1023)
Entity's Momentum: -0.03, -0.08, -0.03
Entity's Passengers: []
Entity's Vehicle: null
Stacktrace:
at net.minecraft.class_1937.method_18472(class_1937.java:480)
at net.minecraft.class_3218.method_31420(class_3218.java:385)
at net.minecraft.class_5574.method_31791(class_5574.java:54)
at net.minecraft.class_3218.method_18765(class_3218.java:353)
at
net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
at
net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:820)
at net.minecraft.class_1132.method_3748(class_1132.java:105)
at
net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
at
net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
All players: 1 total; [class_3222['ItemAsylum_'/3, l='ServerLevel[New
World]', x=738.20, y=69.00, z=906.93]]
Chunk stats: 4418
Level dimension: minecraft:overworld
Level spawn location: World: (16,71,-16), Section: (at 0,7,0 in 1,4,-1;
chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains
chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Level time: 4345892 game time, 161834 day time
Level name: New World
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Level weather: Rain time: 43838 (now: false), thunder time: 8447 (now: true)
Known server brands: fabric
Removed feature flags:
Level was modded: true
Level storage version: 0x04ABD - Anvil
Stacktrace:
at
net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
at
net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:820)
at net.minecraft.class_1132.method_3748(class_1132.java:105)
at
net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
at
net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
Minecraft Version: 1.20.2
Minecraft Version ID: 1.20.2
Operating System: Windows 11 (amd64) version 10.0
Java Version: 17.0.8, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 909350192 bytes (867 MiB) / 2147483648 bytes (2048 MiB) up to
2147483648 bytes (2048 MiB)
CPUs: 8
Processor Vendor: AuthenticAMD
Processor Name: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
Microarchitecture: Zen / Zen+
Frequency (GHz): 2.30
Number of physical packages: 1
Number of physical CPUs: 4
Number of logical CPUs: 8
Graphics card #0 name: AMD Radeon(TM) RX Vega 10 Graphics
Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
Graphics card #0 VRAM (MB): 2048.00
Graphics card #0 deviceId: 0x15d8
Graphics card #0 versionInfo: DriverVersion=31.0.21023.2010
Memory slot #0 capacity (MB): 8192.00
Memory slot #0 clockSpeed (GHz): 2.40
Memory slot #0 type: DDR4
Memory slot #1 capacity (MB): 4096.00
Memory slot #1 clockSpeed (GHz): 2.40
Memory slot #1 type: DDR4
Virtual memory max (MB): 25031.30
Virtual memory used (MB): 21496.91
Swap memory total (MB): 14915.05
Swap memory used (MB): 1283.07
JVM Flags: 9 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=32M
Fabric Mods:
bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.3-1.20.2
maelstrom_library: Maelstrom Library 1.6-1.20
multipart_entities: MultipartEntities 1.5-1.20
cardinal-components: Cardinal Components API 5.3.0
cardinal-components-base: Cardinal Components API (base) 5.3.0
cardinal-components-block: Cardinal Components API (blocks) 5.3.0
cardinal-components-chunk: Cardinal Components API (chunks) 5.3.0
cardinal-components-entity: Cardinal Components API (entities) 5.3.0
cardinal-components-item: Cardinal Components API (items) 5.3.0
cardinal-components-level: Cardinal Components API (world saves) 5.3.0
cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.3.0
cardinal-components-world: Cardinal Components API (worlds) 5.3.0
cloth-config: Cloth Config v12 12.0.109
cloth-basic-math: cloth-basic-math 0.6.1
continuity: Continuity 3.0.0-beta.4+1.20.2
elementa: Elementa 604
essential: Essential 14099+deploy-staging+g4e34fe63b
essential-container: essential-container 1.0.0
essential-loader: essential-loader 1.2.1
fabric-api: Fabric API 0.90.0+1.20.2
fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.41+fce67b32a0
fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+661cc8c6a0
fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1)
1.1.43+f4b7e424a0
fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
fabric-command-api-v1: Fabric Command API (v1) 1.2.36+f71b366fa0
fabric-command-api-v2: Fabric Command API (v2) 2.2.15+86b12645a0
fabric-commands-v0: Fabric Commands (v0) 0.2.53+df3654b3a0
fabric-containers-v0: Fabric Containers (v0) 0.1.73+df3654b3a0
fabric-content-registries-v0: Fabric Content Registries (v0)
5.0.4+285022b3a0
fabric-convention-tags-v1: Fabric Convention Tags 1.5.7+f4b7e424a0
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
fabric-data-generation-api-v1: Fabric Data Generation API (v1)
13.1.3+e3d2bf3fa0
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.56+b1229956a0
fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.25+f4b7e424a0
fabric-events-interaction-v0: Fabric Events Interaction (v0)
0.6.9+daef22a2a0
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.68+df3654b3a0
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+f4b7e424a0
fabric-item-api-v1: Fabric Item API (v1) 2.1.32+43511215a0
fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.14+e3d2bf3fa0
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.26+3bafade3a0
fabric-loot-api-v2: Fabric Loot API (v2) 2.1.0+3ba460fba0
fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.54+f4b7e424a0
fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.5+f4b7e424a0
fabric-models-v0: Fabric Models (v0) 0.4.4+9386d8a7a0
fabric-networking-api-v1: Fabric Networking API (v1) 3.0.9+e3d2bf3fa0
fabric-object-builder-api-v1: Fabric Object Builder API (v1)
12.1.1+b1b4f7b0a0
fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.6+96509552a0
fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.4+34a3e0e2a0
fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
fabric-renderer-registries-v1: Fabric Renderer Registries (v1)
3.2.48+df3654b3a0
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1)
0.3.39+73761d2ea0
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
fabric-rendering-v0: Fabric Rendering (v0) 1.1.51+df3654b3a0
fabric-rendering-v1: Fabric Rendering (v1) 3.0.10+86b12645a0
fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1)
2.3.10+e3d2bf3fa0
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.11+86b12645a0
fabric-screen-api-v1: Fabric Screen API (v1) 2.0.11+0ba8e9cea0
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1)
1.3.39+86b12645a0
fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.8+109a65e5a0
fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners
(v1) 5.0.3+fce67b32a0
fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm:
kotlinx-coroutines-core-jvm 1.7.3
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm:
kotlinx-serialization-cbor-jvm 1.6.0
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm:
kotlinx-serialization-core-jvm 1.6.0
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm:
kotlinx-serialization-json-jvm 1.6.0
fabricloader: Fabric Loader 0.14.23
fallingtree: FallingTree 5.0.2
ferritecore: FerriteCore 6.0.0
geckolib: GeckoLib 4 4.2.3
com_eliotlash_mclib_mclib: mclib 20
imst: Immersive structures 2.1.0
indium: Indium 1.0.27+mc1.20.1
iris: Iris 1.6.10
io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
org_anarres_jcpp: jcpp 1.4.14
org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
java: OpenJDK 64-Bit Server VM 17
lithium: Lithium 0.12.0
minecraft: Minecraft 1.20.2
modmenu: Mod Menu 8.0.0
org_jetbrains_annotations: annotations 13.0
reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.2-build.96
sodium: Sodium 0.5.3
soulsweapons: Marium's Soulslike Weaponry 0.9.9.7-1.20-fabric
ultris_mr: Ultris: Boss Expansion 5.6.9b
universalcraft: UniversalCraft 312
universalcraft: UniversalCraft 211
uselessreptile: Useless Reptile 0.6.0-1.20.2
common-protection-api: Common Protection API 1.0.0
vigilance: Vigilance 286
wakes: Wakes 0.2.0
blue_endless_jankson: jankson 1.2.2
yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20.2
com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
org_quiltmc_parsers_gson: gson 0.2.1
org_quiltmc_parsers_json: json 0.2.1
Loaded Shaderpack: (off)
NEC status: No NEC detected
Server Running: true
Player Count: 1 / 8; [class_3222['ItemAsylum_'/3, l='ServerLevel[New
World]', x=738.20, y=69.00, z=906.93]]
Data Packs: vanilla, fabric,
file/spawnanimations-v1.9.2-mc1.17x-1.20x-datapack.zip (incompatible)
Enabled Feature Flags: minecraft:vanilla
World Generation: Stable
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fabric'; Server brand
changed to 'fabric'
Launched Version: fabric-loader-0.14.23-1.20.2

**Comment by mariumbacchus** [comment]
Huh, very odd. Did you just spawn it or what happened right before the crash?

**Comment by ItemAsylum** [comment]
i just summoned it with the weapon after getting sum souls

**Comment by ItemAsylum** [comment]
btw i farmed the souls from wardens if that's useful (dont ask why)before
summoning it

**Comment by mariumbacchus** [comment]
Hopefully just a onetime issue, can't seem to recreate the issue. Thanks for the heads up though :)

**Comment by ItemAsylum** [comment]
alr ty for your time. it probly is a one time issue since i cant recreate
it as well
