### ISSUE TITLE
BossCompass Crashes Server

### ISSUE THREAD

**Issue by ereese99** [mariumbacchus/Soulslike-Weaponry#7]
Fabric 0.14.17, Minecraft 1.19.2, Mod Version 0.9.8

Crashes the server upon usage
[crash-2023-03-14_02.43.46-server.txt](https://github.com/mariumbacchus/Soulslike-Weaponry/files/10980180/crash-2023-03-14_02.43.46-server.txt)

**Comment by mariumbacchus** [comment]
Can't seem to recreate the issue. Can you tell me step by step how you found the bug?

**Comment by mariumbacchus** [comment]
Just found an article about the "Watchdog" crash that you got ([read here](https://www.mysysadmintips.com/windows/home-and-media/556-minecraft-server-crashes-server-watchdog-fatal-a-single-server-tick)). Maybe that will help.

**Comment by mariumbacchus** [comment]
From what I can gather, it seems that Watchdog errors mean that the server tried to do more in a single tick than your CPU could do in a set period of time. I'll reduce the tick rate for the Moonstone Compass, as it may have been ticked multiple times accidentally which overloaded your pc or server.
