### ISSUE TITLE
Error when using right click ability with Genesis Fracture

### ISSUE THREAD

**Issue by SwedishAddict** [mariumbacchus/Soulslike-Weaponry#72]
This is using the latest version of the mod for Fabric 1.20.1

Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7972()" because "stack" is null

Here is the full crash report:

[crash-2023-11-19_00.12.36-server.txt](https://github.com/mariumbacchus/Soulslike-Weaponry/files/13401706/crash-2023-11-19_00.12.36-server.txt)

**Comment by mariumbacchus** [comment]
Fixed in new patch.
