### ISSUE TITLE
Incompatibility with MajruszLibrary

### ISSUE THREAD

**Issue by Mysterious-Wrangler** [mariumbacchus/Soulslike-Weaponry#73]
Fabric 1.20.1
Curseforge modloader version of fabric 0.14.24
Mod: soulslike-weaponry-1.0.0-1.20-fabric.jar

Crash at end of log, attached file. It crashed when i updated the mod.
[2023-11-18-1.log](https://github.com/mariumbacchus/Soulslike-Weaponry/files/13402358/2023-11-18-1.log)

**Comment by mariumbacchus** [comment]
Seems to be a conflict issue between Majrusz Library and SW. I'll look into it.

**Comment by Majrusz** [comment]
Hello, I fixed it on my side and our mods should be compatible now when used with Majrusz Library 7.0.1+

**Comment by mariumbacchus** [comment]
Thanks for the reply! I will update SW soon to implement my changes as well.
