### ISSUE TITLE
SW 1.0.0 for 1.19.2 is incompatible with Spell Engine (and, subsequently, Wizards (RPG Series))

### ISSUE THREAD

**Issue by a-lakeside-viewer** [mariumbacchus/Soulslike-Weaponry#74]
Good day! Not sure if compatibility is a priority for the mod but I might as well bring it up.

SW will run if [Spell Engine](https://www.curseforge.com/minecraft/mc-mods/spell-engine) is installed. However, all right-click abilities of the weapons are removed/become non-functional. 

Edit:
I would also like to add that I have opened the configs of spell engine and disabled the config which makes all sword weapons able to cast spells

**Comment by mariumbacchus** [comment]
I am unable to recreate this issue. Are you saying that the weapons abilities no longer works or you cannot use the spells of spell engine while holding the weapon?

What is intended by default is that spells cannot be cast when holding weapons from this mod, since that caused other issues.

**Comment by a-lakeside-viewer** [comment]
Apologies, I didn't even include the version of spell engine I was using. Due to another mod requiring this specific version, I am using 'spell_engine-fabric-0.9.25+1.19'. If this mod is present, the 'Cast spells from Spell Book' appears at the bottom text of the soulsweapons lore text. This makes it unable to use the abilities (Particularly, the right-click abilities like Nightfall. However, R ALT for Night's Edge still works, for example) (weirdly enough, The Darkin Scythe can still use the right-click ability though). 

Going into the configs of spell engine and changing the 'add_spell_casting_to_swords' to false removes the bottom text of  'Cast spells from Spell Book' but the right-click abilities of SW weapons are still non-functional.

**Comment by mariumbacchus** [comment]
Seems to be an issue with older versions of spell engine. I've done what I can to fix the issue, but it has no effect on older versions sadly. Updating would be the best fix.
