### ISSUE TITLE
Chaos orb

### ISSUE THREAD

**Issue by TheDarkUmbra** [mariumbacchus/Soulslike-Weaponry#79]
I'm not sure if this is just me not doing something right but for some reason I can't throw the chaos orb to summon the Day Stalker and the Night Prowler. I'm not sure why this is, I don't know if I'm just pressing the wrong button, I'm just not really sure.

**Comment by mariumbacchus** [comment]
Do you have other mods that may cause the conflict?

**Comment by TheDarkUmbra** [comment]
I'm honestly not sure, everything else in the mod has been working perfectly fine so I don't think there are any mods causing problems. I have absolutely no idea tbh.

**Comment by mariumbacchus** [comment]
What version of the mod are you playing?

**Comment by TheDarkUmbra** [comment]
well the mod file is called soulslike-weaponry-0.9.9.6-patch-2-1.20-fabric so I assume version 0.9.9.6

**Comment by TheDarkUmbra** [comment]
sorry, accidentally closed it then

**Comment by TheDarkUmbra** [comment]
sorry, accidentally closed it then

**Comment by TheDarkUmbra** [comment]
I swapped the mod file for the newest version of the mod and it seems to have fixed the problem cos i just threw the chaos orb and it worked, thanks!

**Comment by mariumbacchus** [comment]
Yeah sounded like you forgot to update, glad I could help.
