### ISSUE TITLE
Gearifiers Mild Incompat

### ISSUE THREAD

**Issue by ereese99** [mariumbacchus/Soulslike-Weaponry#8]
Gearifiers mod by fzzyhamsters are showing on, but not working on soulslike items (specifically the Cape of Chaos, not sure what all else)

**Comment by mariumbacchus** [comment]
To me, it looks like the mod is missing documentation for a proper fix/compatibility (the link to the wiki doesn't even work, as of now). In short, I will not be able to fix the issue until the mod developer adds documentation to fix compatibility issues, would be really nice if he could add compatibility through jsons, like how Better Combat does it.
