### ISSUE TITLE
[Feature Request] Projectile Damage Integration + Configurable Bow Attributes

### ISSUE THREAD

**Issue by muon-rw** [mariumbacchus/Soulslike-Weaponry#80]
Title says it all - To give bows (and guns) similar configurability and strength to the other weapons, I recommend either bundling/depending on Projectile Damage Attribute (it's very lightweight and commonly bundled). 

It could also apply optionally if the mod is loaded.

**Comment by mariumbacchus** [comment]
Implemented Projectile Damage Attribute for all versions except 1.20.1 which uses Ranged Weapon API, will be up next update.
