### ISSUE TITLE
[Bug] [Mod Incompat?] Boss Health does not increase at all

### ISSUE THREAD

**Issue by muon-rw** [mariumbacchus/Soulslike-Weaponry#81]
When increasing boss health via the config, it does not change from the default. 
I tested specifically with the decaying king/accursed_lord_boss

In addition, other mods that modify entity HP (dungeon difficulty, RPG difficulty, etc.) do not apply to spawned soulsweapons bosses. These are the only entities in my pack where this is the case. 

I have not tested this outside of my modpack environment, if you can't reproduce it I can send a mod list. 

Edit: Worth noting that I have recently regenerated my config. It is up to date and formatted properly. Other aspects of the config such as item stats do work.

**Comment by KevzCz** [comment]
@mariumbacchus do the bosses have the tag: "c:bosses"
![image](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/130611225/bbf9e9bc-6047-47e9-8bb7-d688be3cbd47)
this was in rpgdifficulty datapack section

**Comment by mariumbacchus** [comment]
No they aren't, thanks for the heads up, although there is a bigger issue regarding the HP and customizing it to higher values in the config. 
Mojang decided to hard-cap the max GENERIC_MAX_HEALTH value to 1024, so in the meantime, my solution was to override the whole value via a mixin. I did know then I would need a different solution soon, and that time has come now. I can either ignore it completely so it will always be capped at 1024 so it can be easily compatible with other mods, or figure something else out.

I'll look into it when I can.

**Comment by KevzCz** [comment]
pretty sure AttributeFix fixes that max health problem

**Comment by mariumbacchus** [comment]
It sure does, but I find it kinda annoying to have so many relations/external libraries. I suppose I could use it though.
