### ISSUE TITLE
[Suggestion] [1.19.2/1.20.1] Better Draupnir Spear Animations and Attacks with Better Combat.

### ISSUE THREAD

**Issue by Jiyu-Shimizu** [mariumbacchus/Soulslike-Weaponry#84]
I suggest editing the animations for the Draupnir Spear to better represent how it's used in GoW: Ragnarok. Instead of just a repeating thrusting/stabbing animation, maybe add some slashes from left, right, and above as if it was being swung like a sword? Being able to summon a volley of spears from above via an extra ability would be nice to see, if possible.

**Comment by mariumbacchus** [comment]
Added the requested ability and changed attacks, will be live next update.
