### ISSUE TITLE
Disallow boss from droping weapons

### ISSUE THREAD

**Issue by DoubL753** [mariumbacchus/Soulslike-Weaponry#87]
Hi, just wondering how to change the boss loot table... I'm trying to make it so they don't drop their weapons, while keeping the other drops ! But looking in the loot_tables, i couldn't find it... And disabling the recipe for the weapons doesn't change that. Is it possible ?

**Comment by mariumbacchus** [comment]
I've kinda hardcoded the drops of the bosses. I didn't really think anyone would want to remove them so it didn't cross my mind. I'll look into a fix.

**Comment by DoubL753** [comment]
Thanks :D

**Comment by mariumbacchus** [comment]
Loot table jsons now generate with the drops of the bosses. As of now, they all will _always_  drop their loot regardless of how they died.
