### ISSUE TITLE
Throwable weapons such as the Mjolnir and the Leviathan do not return to the player and disappear when thrown at random times.

### ISSUE THREAD

**Issue by MagentaMiso** [mariumbacchus/Soulslike-Weaponry#89]
What the title states, this has happened to us roughly 4 times each in the past 24 hours and we cannot figure out what triggers the bug. Playing on version 1.0.2-1.20 Fabric, in the Prominence II modpack on curseforge.

It is a shame as we are loving this mod and we find these two weapons to be our favorite from the bunch by far (we also love the little secret feature that happens when they collide head on against each other) so we are hoping this can be fixed as otherwise it makes the weapons completely unreliable!

**Comment by mariumbacchus** [comment]
That's odd. What did you do when you threw it and it disappeared? Did you throw it near a nether portal? Into an unloaded chunk? Did you have full inventory when trying to pick it up? Or did you simply just throw it at something and it randomly disappeared?

**Comment by mariumbacchus** [comment]
Thanks for the update! It does sound like there is a weird interaction between that backback slot and the insertion of the item (it is supposed to fill the first open slot so maybe that mod makes it prioritize that slot).

When it comes to the thrown damage, it is indeed scaling, but it seems that I made an oversight making it deal far less damage with Sharpness and more with Smite and BOA. I must've forgot that the axe can't get those enchants ¯\_(ツ)_/¯. 

I'll make sure the damage is fixed in the next update.

**Comment by MagentaMiso** [comment]
Thank you! Looking forward to the update! I've been exclusively using this weapon for my current playthrough and it really is a lot of fun! 👍 👍 

I've been wanting to add that I have in mind two suggestions that could improve the experience and make combat more dynamic if you are interested! Faithful to the GoW game, I thought it would be really interesting if the Leviathan and maybe the Mjolnir could damage obstructing enemies on its way back to the player,  in addition to that make the weapons return at will, making them able to be left stuck on a block (Similar to how the Draupnir spear stays put on impact with a block). The damaging on its way back idea was actually brought up by someone watching me play and since then I thought it could really make the weapon feel complete! 

It's a suggestion, I don't know whether it is possible to even code or if you have the time to do so, regardless it is an amazing mod and I really appreciate the work you put into it! ^^ 

Once again thank you for the quick response and I hope you have an enjoyable weekend! 🤟

**Comment by mariumbacchus** [comment]
Those interactions sound awesome. I'll look into it and see what I can do.

**Comment by mariumbacchus** [comment]
Mjolnir and Leviathan Axe now trigger damaging effects when colliding on the way back and must be called back by pressing a keybind (N) or picked up manually.
