### ISSUE TITLE
YIGD Compat

### ISSUE THREAD

**Issue by jmadarg** [mariumbacchus/Soulslike-Weaponry#9]
Not really an issue of this mod, but the dev of [YIGD](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger) said this may be easier to fix on this side.

The issue:
On the server I help to manage there has been reports from 2 players of the Fallen Icon being able to break their graves. I personally haven't been able to test it yet, so not exactly sure how they break it and if its only the Fallen Icon.
YIGD dev proposed as solution to add the graves as a block these bosses can't break.

Thanks in advance!

**Comment by mariumbacchus** [comment]
Noted, I'll look into it.

**Comment by FudoriMoru** [comment]
Yes, i have the same problem. and another problem with the boss himself. When I go back to the boss he was frozen in time, not taking damage or attacking me but just standing there like a statue. I'm getting explained that the boss try to kill me and broke my grave at the same time and it bugs out his AI to think his target is dead and go back to standby mode
![image](https://user-images.githubusercontent.com/104599934/230727317-eb80b98f-dec1-4dd8-92dd-89e7fd108aa4.png)
