### ISSUE TITLE
Darkmoon Bow projectiles passing through entities at close range

### ISSUE THREAD

**Issue by car45167** [mariumbacchus/Soulslike-Weaponry#91]
Hi i m using the mod with connector and just noticed that firing an arrow with darkmoon longbow from a short distance just make the arrow rebounce off the mob without taking any damage, can you check this? Also mijolnir , leviathan don t return to hand and just fly around the character. As a suggestion, is it possible to make the arrows of the bows 3D, if it s simple enough i mean.

**Comment by mariumbacchus** [comment]
Can't seem to recreate the issue with Mjolnir and Leviathan Axe, but I see issue with the Darkmoon Bow, and I'll look into a fix. 
I won't change the arrow models to 3D, I'm happy with how they look right now, and they would just look goofy when packed up together with the Arrow Storm.

**Comment by car45167** [comment]
Thank you, mijolnir and leviathan show like this
![image](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/143258160/09d72f15-084b-4310-bab1-14592e97bc95)

**Comment by mariumbacchus** [comment]
There is likely another mod that creates this conflict. Do you have any mod that adds other inventory spaces?

**Comment by car45167** [comment]
I have sophisticated backpack but i tried to remove it and the problem persists. Probably some other mods?

**Comment by mariumbacchus** [comment]
Most likely. If the items never enter your inventory, then there is something else causing the issue.

**Comment by mariumbacchus** [comment]
Did you find the culprit mod or does it happen regardless?

**Comment by car45167** [comment]
No man i didn t fins it, the modpack is called calamity 2 rpg on curseforge if you want to try

**Comment by car45167** [comment]
Man i have tried to disable some mods but i didn't find the culprit. Here is the list:
1)Cosmetic Armor Reworked
2)YDM Weapon Master
3)Sophisticated Backpack
4)Trash Slot
5)Inventory HUD+
6)Simple Inventory Sorter
7)Craft Tweaker
8)Mouse tweaker
9)Better third person
10)Auto third person
11)Create and addons
12)Corpse
13)Apotheosis
14)Climb ladder faster
15)Not enough animation
16)Essentials
17)Relics

As you can see a lot of these mods are about HUD, Inventory and Animation.

**Comment by mariumbacchus** [comment]
If they just float around you like that and refuse to enter the inventory, then I have no idea what could be causing it besides other conflicting mods. I am unable to recreate the issue either. If there is a log (like server log or something) that could maybe contain error messages about the bug then I could look into it more.

**Comment by mariumbacchus** [comment]
No problem, bugs like these can pop up at any time. It's always hard to know how different mods interact with each other, so publishing issue posts like these raises awareness for me to fix the issues (or at least I try).
