### ISSUE TITLE
Client size crash when next to some bosses

### ISSUE THREAD

**Issue by DoubL753** [mariumbacchus/Soulslike-Weaponry#92]
I had this issues on my server where some attacks the bosses does just straight up crash the client size of poeple around them. Not just disconnecting them but downright crash their games. The issue happens mostly when facing the Night Prowler, when using the Blackflame Snake attack. I'm staring to wonder if it's because it's creating too much particules or something like that, and overload the client because it cannot handle it, but i'm not sure, and i'm not sure anyone have the same problem as I have. It's not a constant thing, it doesn't happen everytime the Prowler does the attack, but when fighting them I just know I have 3/4 chance of my game doing that.

**Comment by mariumbacchus** [comment]
Turn particles off in the settings and see if that changes anything. Also provide with a crash log if you have one.

**Comment by mariumbacchus** [comment]
I can't solve any of the issues with no crash log. Will be closed soon if no log is provided.

**Comment by DoubL753** [comment]
[hs_err_pid6496.log](https://github.com/mariumbacchus/Soulslike-Weaponry/files/14503166/hs_err_pid6496.log)
Sorry for the long delay, some things came up in between, here you go !

> I can't solve any of the issues with no crash log. Will be closed soon if no log is provided.

**Comment by mariumbacchus** [comment]
This log is really weird, minecraft crash logs don't usually look like this, this is a core java issue I am guessing (or not, not sure). The only minecraft related things that are being called are inventory methods being used. Maybe this could be you running out of memory? It doesn't really tell me anything at all, it doesn't even mention soulsweaponry. Let me know if the issue persists and if you get another log.
