### ISSUE TITLE
Visual Bug with Arkenplate and Better Combat

### ISSUE THREAD

**Issue by BigProblem4** [mariumbacchus/Soulslike-Weaponry#95]
When wielding weapons that are two handed, it causes weird visual bug with Arkenplate
![2024-02-23_00 17 00](https://github.com/mariumbacchus/Soulslike-Weaponry/assets/160975349/7a281b00-4e03-436e-a1db-0ffb970612b6)

**Comment by mariumbacchus** [comment]
What version of minecraft, soulslike weaponry and better combat were you playing?

**Comment by BigProblem4** [comment]
fabric 1.20.1
soulslike 1.0.2-1.20-fabric
bettercombat 1.8.4+1.20.1

2024-02-23, pn, 21:55 mariumbacchus ***@***.***> rašė:

**Comment by mariumbacchus** [comment]
Thanks, I'll look into it soon.
