### ISSUE TITLE
Prevent bleed on modded skeleton mobs

### ISSUE THREAD

**Issue by NolanHewitt** [mariumbacchus/Soulslike-Weaponry#96]
Bleed doesn't apply to skeleton mobs which makes sense, but is there a way to make this also true for modded skeleton enemies through a datapack?

**Comment by mariumbacchus** [comment]
I was hoping other mods would simply extend the AbstractSkeleton class so this wouldn't be an issue, but I guess people don't do that. I'll see what I can do about it.

**Comment by NolanHewitt** [comment]
Thank you, the particular mod I’m looking at is “the graveyard” mod which I first noticed with its skeleton creepers, but I think it has a few other skeleton mobs as well.

**Comment by mariumbacchus** [comment]
Made it check the tags instead when dealing damage.
